import Foundation
import SwiftUI

// ⚠️ 本文件由 scripts/gen_skilldata.py 从 CF动作库 xlsx 生成，请勿手改；改数据请更新 xlsx 后重跑脚本。

// MARK: - SkillTier

enum SkillTier: String, CaseIterable, Identifiable, Codable {
    case l1, l2, l3, l4, l5
    var id: String { rawValue }

    var label: String {
        switch self {
        case .l1: "L1"
        case .l2: "L2"
        case .l3: "L3"
        case .l4: "L4"
        case .l5: "L5"
        }
    }

    var description: String {
        switch self {
        case .l1: "入门"
        case .l2: "基础"
        case .l3: "进阶"
        case .l4: "高阶"
        case .l5: "精英"
        }
    }
}

// MARK: - SkillSubcategoryDefinition

struct SkillSubcategoryDefinition: Identifiable {
    let id: String
    let name: String
    let categoryId: String
}

// MARK: - SkillDefinition

struct SkillDefinition: Identifiable {
    let id: String
    let name: String
    /// 英文名称
    let englishName: String
    let tier: SkillTier
    let categoryId: String
    let subcategoryId: String
    /// 动作模式（= 子类名称，如「核心」「上肢拉(垂直)」）
    let movementPattern: String
    /// 计量方式（次数 / 静力时长 / 距离 …）
    let measure: String
    /// 动作简介
    let intro: String
    /// 动作步骤
    let steps: String
    /// 要点与注意（部分动作有）
    let keyPoints: String?
    /// 降阶替代
    let scaling: String
    /// 前置动作 id
    let prerequisites: [String]
    /// 前置依据
    let prereqRationale: String?
    /// 英文简介 / 步骤 / 要点 / 降阶（来自 xlsx 英文列；空则运行时回退中文）
    let englishIntro: String
    let englishSteps: String
    let englishKeyPoints: String?
    let englishScaling: String
}

// MARK: - SkillCategoryDefinition

struct SkillCategoryDefinition: Identifiable {
    let id: String
    let name: String
    let englishName: String
    let icon: String
    let color: Color
    let subcategories: [SkillSubcategoryDefinition]
    let skills: [SkillDefinition]
}

// MARK: - SkillLibrary

enum SkillLibrary {
    static let categories: [SkillCategoryDefinition] = [gymnastics, weightlifting]

    static var allSkills: [SkillDefinition] { categories.flatMap { $0.skills } }
    static var skillById: [String: SkillDefinition] {
        Dictionary(uniqueKeysWithValues: allSkills.map { ($0.id, $0) })
    }

    /// 已上传示范视频的动作 id（在脚本模板内维护，重跑脚本不丢失）。
    /// 上传新视频到 COS 的 `movements/{id}.mp4` 后，把对应 id 加进来即可生效。
    static let skillsWithVideo: Set<String> = ["row"]

    static func hasVideo(_ skillId: String) -> Bool { skillsWithVideo.contains(skillId) }

    // MARK: 体操 Gymnastics (56)

    static let gymnastics = SkillCategoryDefinition(
        id: "gymnastics",
        name: "体操",
        englishName: "Gymnastics",
        icon: "figure.gymnastics",
        color: Color(hex: "#5BE88F"),
        subcategories: [
            SkillSubcategoryDefinition(id: "gym_m01", name: "核心", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m02", name: "位移有氧", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m03", name: "上肢拉(水平)", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m04", name: "深蹲", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m05", name: "跳跃", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m06", name: "弓步单腿", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m07", name: "复合全身", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m08", name: "上肢推(水平)", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m09", name: "上肢推(过头)", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m10", name: "上肢拉(垂直)", categoryId: "gymnastics"),
            SkillSubcategoryDefinition(id: "gym_m11", name: "上肢拉(垂直)/核心", categoryId: "gymnastics"),
        ],
        skills: gymnasticSkills
    )

    private static let gymnasticSkills: [SkillDefinition] = [
        s("abmat_sit_up", "AbMat仰卧起坐", "gym_m01", .l1, "核心", "次数",
          intro: "用 AbMat 垫支撑腰背的仰卧起坐", steps: "脚底相对、腰下垫 AbMat，起身双手触脚前地面，回落肩胛触地", keyPoints: nil,
          scaling: "屈膝 / 减小幅度", prereqs: [], rationale: "基础动作", englishName: "Abmat Sit Up",
          englishIntro: "A sit-up supported by an AbMat under the lower back", englishSteps: "Set the soles of the feet together with the AbMat under the lower back; sit up and touch both hands to the floor in front of the feet, then lower until the shoulder blades touch the floor",
          englishKeyPoints: nil, englishScaling: "Bend the knees / reduce the range of motion"),
        s("sit_up", "仰卧起坐", "gym_m01", .l1, "核心", "次数",
          intro: "锻炼核心的起坐动作", steps: "仰卧脚底相对、双膝外展，双臂过头触地；起身双手前伸触地，肩胛回落触地", keyPoints: nil,
          scaling: "屈膝仰卧起坐 / 减小幅度", prereqs: [], rationale: "基础动作", englishName: "Sit Up",
          englishIntro: "A core sit-up movement", englishSteps: "Lie supine with the soles of the feet together and knees out; reach the arms overhead to touch the floor, sit up and reach forward to touch the floor, then lower until the shoulder blades touch the floor",
          englishKeyPoints: nil, englishScaling: "Bent-knee sit-up / reduce the range of motion"),
        s("row", "划船", "gym_m02", .l1, "位移有氧", "距离/卡路里",
          intro: "使用划船机完成有氧输出", steps: "蹬腿—后倒—拉手柄至肋下，再伸臂—前倾—收腿回位，保持连贯节奏", keyPoints: nil,
          scaling: "降低目标距离或时间", prereqs: [], rationale: "基础动作", englishName: "Row",
          englishIntro: "A conditioning (cardio) effort performed on a rowing machine", englishSteps: "Drive with the legs, lean back, and pull the handle to the lower ribs; then extend the arms, hinge forward, and bend the knees to return, keeping a smooth rhythm",
          englishKeyPoints: nil, englishScaling: "Reduce the target distance or time"),
        s("single_under", "单摇跳绳", "gym_m02", .l1, "位移有氧", "次数",
          intro: "每次起跳绳子绕身一圈的跳绳", steps: "前脚掌轻跳、用手腕摇绳，每跳一次绳过脚一次，保持节奏", keyPoints: "前脚掌轻跳、手腕摇绳；适合各水平的入门有氧",
          scaling: "原地跳+甩绳分解 / 减少次数", prereqs: [], rationale: "基础动作", englishName: "Single Under",
          englishIntro: "A jump-rope movement where the rope passes once per jump", englishSteps: "Jump lightly on the balls of the feet and turn the rope with the wrists; the rope passes under the feet once per jump while you maintain rhythm",
          englishKeyPoints: "Jump lightly on the balls of the feet and turn the rope with the wrists; a beginner-friendly conditioning movement for all levels", englishScaling: "Jump in place and practice the rope turn separately / reduce reps"),
        s("ring_row", "吊环划船", "gym_m03", .l1, "上肢拉(水平)", "次数",
          intro: "握吊环身体后倾完成的水平拉力动作", steps: "握环身体后倾成直线，把胸尽量拉向吊环，控制放回，环越低越难", keyPoints: "吊环训练入门动作，也是引体向上的进阶过渡；吊环越低越难",
          scaling: "升高吊环减难 / 屈膝减难", prereqs: [], rationale: "基础动作", englishName: "Ring Row",
          englishIntro: "A horizontal pulling movement performed with the body leaning back while holding rings", englishSteps: "Hold the rings and lean back with the body in a straight line; pull the chest toward the rings, then lower under control. The lower the rings, the harder the movement",
          englishKeyPoints: "An entry-level ring movement and a useful progression toward pull-ups; the lower the rings, the harder it becomes", englishScaling: "Raise the rings to make it easier / bend the knees to make it easier"),
        s("air_squat", "徒手深蹲", "gym_m04", .l1, "深蹲", "次数",
          intro: "无负重的基础深蹲", steps: "双脚与肩同宽，屈髋屈膝下蹲至髋低于膝，膝随脚尖外展，蹬地站直", keyPoints: "学习正确深蹲的最佳方式是先无负重打好动作基础",
          scaling: "扶撑深蹲 / 坐箱深蹲", prereqs: [], rationale: "基础动作", englishName: "Air Squat",
          englishIntro: "A foundational bodyweight squat", englishSteps: "Stand with feet about shoulder-width apart; send the hips and knees down until the hips are below the knees, track the knees over the toes, then drive through the floor to stand tall",
          englishKeyPoints: "The best way to learn proper squat mechanics is to build the movement pattern first without load", englishScaling: "Supported squat / box squat"),
        s("shuttle_sprint", "折返跑", "gym_m02", .l1, "位移有氧", "距离/次数",
          intro: "在标志物间往返冲刺", steps: "在标志物间全力冲刺折返，转身减速时控制身体，按要求完成距离或次数", keyPoints: "在安全地面进行、做好热身、穿合适鞋；折返距离宜短（≤15-20 米）",
          scaling: "缩短折返距离", prereqs: [], rationale: "基础动作", englishName: "Shuttle Sprint",
          englishIntro: "A back-and-forth sprint between markers", englishSteps: "Sprint hard between markers; control the body as you decelerate and turn, completing the prescribed distance or reps",
          englishKeyPoints: "Use a safe surface, warm up properly, and wear appropriate shoes; shuttle distances should generally stay short (15-20 m or less)", englishScaling: "Shorten the shuttle distance"),
        s("star_jump", "星跳", "gym_m05", .l1, "跳跃", "次数",
          intro: "跳起四肢张开成星形的爆发动作", steps: "微蹲后尽力跳高，空中伸展四肢成星形，收回四肢屈膝落地", keyPoints: "增强式跳跃，提升爆发力与垂直弹跳",
          scaling: "开合跳 / 减小幅度", prereqs: [], rationale: "基础动作", englishName: "Star Jump",
          englishIntro: "An explosive jump where the limbs open into a star shape", englishSteps: "Dip slightly, jump as high as possible, open the arms and legs into a star shape in the air, then pull them back in and land with bent knees",
          englishKeyPoints: "A plyometric jump that develops power and vertical jump capacity", englishScaling: "Jumping jack / reduce the range of motion"),
        s("bear_crawl", "熊爬", "gym_m01", .l1, "核心", "距离",
          intro: "四肢着地、膝离地的爬行动作", steps: "手在肩下、膝离地约一拳，对侧手脚协同向前爬行，保持背平、髋不晃", keyPoints: "常见错误：拱背、膝抬过高、膝超肘、髋部左右晃动",
          scaling: "缩短距离 / 慢速", prereqs: [], rationale: "基础动作", englishName: "Bear Crawl",
          englishIntro: "A quadruped crawl with the knees lifted off the floor", englishSteps: "Place hands under shoulders and lift the knees about a fist off the floor; crawl forward with opposite hand and foot moving together, keeping the back flat and hips steady",
          englishKeyPoints: "Common faults: rounded back, knees lifted too high, knees passing the elbows, and hips shifting side to side", englishScaling: "Shorten the distance / move slowly"),
        s("walking_lunge", "行走弓步", "gym_m06", .l1, "弓步单腿", "次数",
          intro: "向前行进的弓步", steps: "向前迈步下蹲至后膝近地，前膝对准脚尖，蹬前脚起身收步，换腿交替前进", keyPoints: nil,
          scaling: "原地分腿蹲 / 减小步幅", prereqs: ["air_squat"], rationale: "CF通用进阶", englishName: "Walking Lunge",
          englishIntro: "A forward-moving lunge", englishSteps: "Step forward and lower until the back knee is close to the floor; keep the front knee tracking over the toes, drive through the front foot to stand, then alternate legs",
          englishKeyPoints: nil, englishScaling: "Stationary split squat / shorten the stride"),
        s("box_step_up", "踏箱上步", "gym_m06", .l1, "弓步单腿", "次数",
          intro: "单脚踩上跳箱再站起的动作", steps: "一脚踏满箱面、重心压脚跟蹬起站直，控制下落，换腿交替", keyPoints: "重心压脚跟、勿压脚趾；膝保持在脚趾后方",
          scaling: "降低箱高 / 扶撑", prereqs: [], rationale: "基础动作", englishName: "Box Step Up",
          englishIntro: "A single-leg step onto a box followed by standing tall", englishSteps: "Plant the whole foot flat on the box, drive through the heel to stand tall, lower under control, and alternate legs",
          englishKeyPoints: "Drive through the heel, not the toes; keep the knee behind the toes", englishScaling: "Lower the box / use support"),
        s("assault_bike", "风阻单车", "gym_m02", .l1, "位移有氧", "卡路里",
          intro: "用风阻单车完成骑行输出", steps: "坐稳握把，腿部踩踏配合手臂推拉持续发力，按目标完成卡路里或时间", keyPoints: nil,
          scaling: "降低卡路里或时间目标", prereqs: [], rationale: "基础动作", englishName: "Assault Bike",
          englishIntro: "A conditioning (cardio) effort performed on an air bike", englishSteps: "Sit securely and hold the handles; pedal with the legs while pushing and pulling with the arms, continuing until the target calories or time is completed",
          englishKeyPoints: nil, englishScaling: "Reduce the calorie or time target"),
        s("lateral_burpee", "侧向波比跳", "gym_m07", .l2, "复合全身", "次数",
          intro: "波比跳后侧向跳过杠铃", steps: "完成一次波比跳，起身侧向跳过杠铃，从另一侧进入下一次", keyPoints: nil,
          scaling: "去侧跳 / 踏步波比", prereqs: ["burpee"], rationale: "CF通用进阶", englishName: "Lateral Burpee",
          englishIntro: "A burpee followed by a lateral jump over the barbell", englishSteps: "Complete one burpee, stand up, jump laterally over the barbell, and begin the next rep on the other side",
          englishKeyPoints: nil, englishScaling: "Remove the lateral jump / step-style burpee"),
        s("push_up", "俯卧撑", "gym_m08", .l2, "上肢推(水平)", "次数",
          intro: "双手撑地的上肢推力基础动作", steps: "双手位于肩下、核心收紧，身体成直线下降至胸部接近地面，再推起至手臂伸直", keyPoints: nil,
          scaling: "膝盖俯卧撑 / 斜面（手扶箱）俯卧撑", prereqs: [], rationale: "基础动作", englishName: "Push Up",
          englishIntro: "A foundational upper-body pushing movement from the floor", englishSteps: "Place the hands under the shoulders and brace the core; keep the body in a straight line, lower until the chest is near the floor, then press back up until the arms are straight",
          englishKeyPoints: nil, englishScaling: "Knee push-up / incline push-up (hands on a box)"),
        s("sprint", "冲刺跑", "gym_m02", .l2, "位移有氧", "距离/时间",
          intro: "短距离全力快跑", steps: "身体前倾、前脚掌发力，加大步频与摆臂，全力冲刺至指定距离", keyPoints: nil,
          scaling: "降低距离 / 改快走", prereqs: [], rationale: "基础动作", englishName: "Sprint",
          englishIntro: "An all-out short-distance run", englishSteps: "Lean slightly forward, drive off the balls of the feet, increase cadence and arm swing, and sprint hard to the target distance",
          englishKeyPoints: nil, englishScaling: "Reduce the distance / switch to a fast walk"),
        s("forward_roll", "前滚翻", "gym_m07", .l2, "复合全身", "次数",
          intro: "收头团身向前翻滚的技巧动作", steps: "下蹲撑手、收下巴拱背，蹬地使髋越头团身滚动，顺势收腿起身站立", keyPoints: "收下巴、勿让头顶触地以保护头颈；高风险技巧，建议配合视频并注意安全",
          scaling: "斜面辅助滚翻 / 团身练习", prereqs: [], rationale: "基础动作", englishName: "Forward Roll",
          englishIntro: "A skill movement that rolls forward from a tucked position", englishSteps: "Squat down and place the hands on the floor; tuck the chin, round the back, push off the floor, roll with the hips passing over the head, then bring the feet under you and stand",
          englishKeyPoints: "Tuck the chin and keep the top of the head off the floor to protect the neck; this is a higher-risk skill, so use video guidance and train safely", englishScaling: "Incline-assisted roll / tuck practice"),
        s("burpee", "波比跳", "gym_m07", .l2, "复合全身", "次数",
          intro: "由下蹲、俯卧撑与跳跃组成的全身动作", steps: "双手撑地双脚后跳成平板，胸与髋触地；收腿起身向上跳，双臂过头", keyPoints: "CrossFit 标准需胸与髋触地；俯卧撑后脚尖触地、双脚与髋同宽可减小幅度护膝；腰椎疾病或损伤者慎做",
          scaling: "踏步式波比（不跳）/ 去俯卧撑或去跳跃", prereqs: [], rationale: "基础动作", englishName: "Burpee",
          englishIntro: "A full-body movement combining a squat, prone drop, and jump", englishSteps: "Place the hands on the floor and jump the feet back to a plank, with chest and hips touching the floor; jump the feet in, stand, jump upward, and raise the arms overhead",
          englishKeyPoints: "The CrossFit standard requires the chest and hips to touch the floor; after the push-up, touching down on the toes with the feet at hip width and stepping in can reduce the range of motion and spare the knees. Use caution with lumbar spine conditions or injuries", englishScaling: "Step-style burpee (no jump) / remove the push-up or the jump"),
        s("squat_jump", "深蹲跳", "gym_m05", .l2, "跳跃", "次数",
          intro: "深蹲后向上跳起的爆发动作", steps: "下蹲至大腿平行，前脚掌蹬地尽力跳高，屈膝缓冲落地接下一次", keyPoints: "冲击大，膝/背有伤者勿做；脚尖先着地、控制落地以防扭伤",
          scaling: "徒手深蹲 / 减小跳高", prereqs: ["air_squat"], rationale: "CF通用进阶", englishName: "Squat Jump",
          englishIntro: "An explosive jump performed after a squat", englishSteps: "Squat until the thighs are about parallel, drive through the balls of the feet to jump as high as possible, and land softly with bent knees into the next rep",
          englishKeyPoints: "High impact; avoid with knee or back injuries. Land first on the balls of the feet and control the landing to reduce sprain risk", englishScaling: "Air squat / reduce the jump height"),
        s("wall_climb", "爬墙倒立", "gym_m09", .l2, "上肢推(过头)", "次数",
          intro: "脚沿墙向上、身体贴近墙面的攀爬", steps: "脚趾胸部着地，双脚沿墙向上、双手向墙靠近，直至胸贴近墙，再退回", keyPoints: nil,
          scaling: "减少向上步数 / 平板支撑", prereqs: ["push_up"], rationale: "CF通用进阶", englishName: "Wall Climb",
          englishIntro: "A climb in which the feet walk up the wall until the chest is close to the wall", englishSteps: "Start chest and toes on the floor facing away from the wall; walk the feet up the wall and the hands toward the wall until the chest is close to it, then walk back down",
          englishKeyPoints: nil, englishScaling: "Reduce the number of steps up the wall / plank hold"),
        s("knees_to_elbows", "膝触肘", "gym_m01", .l2, "核心", "次数",
          intro: "悬垂将膝盖抬至肘部的核心动作", steps: "双臂伸直悬垂于单杠，向上向后踢腿使膝触碰或接近肘部，控制下放", keyPoints: nil,
          scaling: "悬垂屈膝抬腿 / 平板提膝", prereqs: [], rationale: "CF通用进阶", englishName: "Knees To Elbows",
          englishIntro: "A core movement that raises the knees toward the elbows while hanging", englishSteps: "Hang from the pull-up bar with straight arms; kick the legs up and back so the knees touch or approach the elbows, then lower under control",
          englishKeyPoints: nil, englishScaling: "Hanging knee raise / plank knee tuck"),
        s("box_jump", "跳箱", "gym_m05", .l2, "跳跃", "次数",
          intro: "向上跳上跳箱的下肢爆发动作", steps: "站于箱前屈膝摆臂，爆发跳上箱顶屈膝缓冲，顶端髋膝伸直站直后下箱", keyPoints: "落地屈膝缓冲以降低受伤风险；膝/脊柱疾病或损伤、高血压、植物神经紊乱者慎做",
          scaling: "降低箱高 / 踏箱上步", prereqs: ["air_squat", "squat_jump"], rationale: "CF通用进阶", englishName: "Box Jump",
          englishIntro: "A lower-body power movement that jumps onto a box", englishSteps: "Stand in front of the box, bend the knees, and swing the arms; jump explosively onto the box, land with bent knees, then stand tall with hips and knees extended before stepping down",
          englishKeyPoints: "Land with bent knees to absorb impact and reduce injury risk; use caution with knee or spinal conditions, injuries, hypertension, or autonomic dysfunction", englishScaling: "Lower the box / box step-up"),
        s("hand_release_push_up", "释手俯卧撑", "gym_m08", .l2, "上肢推(水平)", "次数",
          intro: "每次最低点双手离地的俯卧撑", steps: "下降至胸触地，双手短暂离地放松，再放回用力推起至手臂伸直", keyPoints: nil,
          scaling: "膝盖释手俯卧撑 / 普通俯卧撑", prereqs: ["push_up"], rationale: "CF通用进阶", englishName: "Hand Release Push Up",
          englishIntro: "A push-up where the hands briefly leave the floor at the bottom", englishSteps: "Lower until the chest touches the floor, briefly lift the hands off the floor to release, then place them back down and press up until the arms are straight",
          englishKeyPoints: nil, englishScaling: "Knee hand-release push-up / regular push-up"),
        s("bar_facing_burpee", "面对杠铃波比跳", "gym_m07", .l2, "复合全身", "次数",
          intro: "面向杠铃的波比跳并跳过杠铃", steps: "完成一次波比跳，起身双脚跳过杠铃，从另一侧进入下一次", keyPoints: "顶端无需完全伸直；腰椎疾病或损伤者慎做",
          scaling: "去跳杠 / 踏步式波比", prereqs: ["burpee"], rationale: "CF通用进阶", englishName: "Bar Facing Burpee",
          englishIntro: "A burpee facing the barbell followed by a jump over it", englishSteps: "Complete one burpee facing the barbell, then stand and jump over the bar with both feet, starting the next rep on the other side",
          englishKeyPoints: "Full extension at the top is not required; use caution with lumbar spine conditions or injuries", englishScaling: "Remove the bar jump / step-style burpee"),
        s("strict_pull_up", "严格引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "不借摆动、纯靠力量的引体向上", steps: "正握悬垂、身体稳定，仅靠上肢拉至下巴过杠，控制下放至完全伸直", keyPoints: "进阶：吊环划船、离心下放、顶端与悬垂静力保持，逐步过渡到完整动作",
          scaling: "弹力带辅助 / 离心引体 / 吊环划船", prereqs: ["ring_row"], rationale: "源数据", englishName: "Strict Pull Up",
          englishIntro: "A strict pull-up performed without using a kip", englishSteps: "Hang from the bar with an overhand grip and a stable body; pull with the upper body until the chin clears the bar, then lower under control to full arm extension",
          englishKeyPoints: "Progressions include ring rows, eccentric lowers, and top-position or dead-hang holds before building to the full movement", englishScaling: "Band-assisted pull-up / eccentric pull-up / ring row"),
        s("handstand", "倒立", "gym_m09", .l3, "上肢推(过头)", "静力时长",
          intro: "靠墙或自由保持的倒立姿势", steps: "双手撑地、肩部主动撑起，收紧核心保持身体竖直成一线", keyPoints: "进阶：靠墙行走→靠墙踢起→离墙漂浮→自由倒立",
          scaling: "爬墙倒立 / 靠墙倒立", prereqs: ["wall_climb"], rationale: "源数据", englishName: "Handstand",
          englishIntro: "A wall-supported or freestanding inverted hold", englishSteps: "Place the hands on the floor, actively press through the shoulders, brace the core, and hold the body vertically in one line",
          englishKeyPoints: "Progression: wall walks, wall kick-ups, controlled wall float, then freestanding handstand", englishScaling: "Wall climb / wall-supported handstand"),
        s("kipping_pull_up", "借力引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "借身体摆动连续完成的引体向上", steps: "悬垂做弓形—空心摆动蓄力，借髋部发力拉至下巴过杠，控制回摆接下一次", keyPoints: "先能连续完成 8-10 个标准引体再学摆动，否则易伤肩",
          scaling: "严格引体向上 / 弹力带辅助", prereqs: ["strict_pull_up"], rationale: "源数据+CF", englishName: "Kipping Pull Up",
          englishIntro: "A pull-up performed continuously with body swing", englishSteps: "Hang from the bar and cycle an arch-to-hollow swing; use the hips to generate power, pull until the chin clears the bar, and control the backswing into the next rep",
          englishKeyPoints: "Learn the kip only after you can complete 8-10 strict pull-ups in a row; otherwise shoulder injury risk increases", englishScaling: "Strict pull-up / band-assisted pull-up"),
        s("kipping_chest_to_bar_pull_up", "借力胸触杠引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "借摆动使胸触杠的引体向上", steps: "弓形—空心摆动蓄力，爆发上拉使锁骨下方触杠，控制下放接下一次", keyPoints: nil,
          scaling: "借力引体向上 / 拉到下巴过杠", prereqs: ["kipping_pull_up", "chest_to_bar_pull_up"], rationale: "CF通用进阶", englishName: "Kipping Chest To Bar Pull Up",
          englishIntro: "A kipping pull-up where the chest makes contact with the bar", englishSteps: "Cycle an arch-to-hollow swing to build tension, then pull explosively until the area below the collarbone touches the bar; control the descent into the next rep",
          englishKeyPoints: nil, englishScaling: "Kipping pull-up / pull only to chin-over-bar"),
        s("clapping_push_up", "击掌俯卧撑", "gym_m08", .l3, "上肢推(水平)", "次数",
          intro: "爆发推起、空中击掌的俯卧撑", steps: "平板下降至肘约 90 度，用力推起使身体离地、空中击掌，落地接下一次", keyPoints: nil,
          scaling: "爆发俯卧撑（推起离地）/ 俯卧撑", prereqs: ["push_up"], rationale: "CF通用进阶", englishName: "Clapping Push Up",
          englishIntro: "An explosive push-up with a clap in the air", englishSteps: "Lower in a plank until the elbows are about 90 degrees, press explosively so the body leaves the floor, clap in the air, then land and continue into the next rep",
          englishKeyPoints: nil, englishScaling: "Explosive push-up (hands leave the floor) / standard push-up"),
        s("double_under", "双摇跳绳", "gym_m02", .l3, "位移有氧", "次数",
          intro: "每次起跳绳子绕身两圈的跳绳", steps: "身体挺直、双臂收于体侧，用手腕快速摇绳，每跳一次绳过脚两次，前脚掌落地", keyPoints: "建议先能连续完成 100 次以上单摇再学习；用轻型速度绳、选合适绳长，靠手腕控制绳子",
          scaling: "单摇跳绳 / 单-双交替", prereqs: ["single_under"], rationale: "源数据+CF", englishName: "Double Under",
          englishIntro: "A jump-rope movement where the rope passes twice per jump", englishSteps: "Stand tall with the arms close to the sides; turn the rope quickly with the wrists so it passes under the feet twice per jump, landing on the balls of the feet",
          englishKeyPoints: "Build to at least 100 consecutive single unders before learning this movement; use a light speed rope, choose the right rope length, and control the rope with the wrists", englishScaling: "Single under / single-double alternating"),
        s("bar_dip", "双杠臂屈伸", "gym_m09", .l3, "上肢推(过头)", "次数",
          intro: "在双杠上完成的臂屈伸", steps: "支撑于双杠、肘部伸直，屈肘前倾下降至肩低于肘，再伸臂推起", keyPoints: "能做 20 次以上可加负重；力量不足可先做离心（缓慢下放）训练；肩关节损伤或慢性病者慎做",
          scaling: "脚辅助或弹力带臂屈伸 / 离心下放", prereqs: ["push_up"], rationale: "源数据+CF", englishName: "Bar Dip",
          englishIntro: "A dip performed on parallel bars", englishSteps: "Support yourself on the parallel bars with elbows locked; bend the elbows and lean forward until the shoulders are below the elbows, then press back up",
          englishKeyPoints: "Once you can perform more than 20 reps, add load; if strength is limited, start with eccentric lowers. Use caution with shoulder injuries or chronic conditions", englishScaling: "Foot- or band-assisted dip / eccentric lower"),
        s("ring_push_up", "吊环俯卧撑", "gym_m08", .l3, "上肢推(水平)", "次数",
          intro: "双手撑吊环增加不稳定性的俯卧撑", steps: "握吊环身体成直线，屈肘下降至胸与环平齐，再推起至手臂伸直", keyPoints: "调整吊环高度控制难度，吊环越低越难",
          scaling: "升高吊环减难 / 俯卧撑", prereqs: ["push_up"], rationale: "源数据+CF", englishName: "Ring Push Up",
          englishIntro: "A push-up performed with both hands on rings, increasing instability", englishSteps: "Hold the rings with the body in a straight line; bend the elbows and lower until the chest is level with the rings, then press back to straight arms",
          englishKeyPoints: "Adjust ring height to control difficulty; lower rings make the movement harder", englishScaling: "Raise the rings to make it easier / standard push-up"),
        s("ring_pull_up", "吊环引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "握吊环完成的引体向上", steps: "站于环下握环悬垂，屈臂把胸拉向吊环，控制下放，躯干稳定不晃", keyPoints: "可练反握增强手腕，为双力臂做准备",
          scaling: "升高减难 / 严格引体向上", prereqs: ["ring_row", "strict_pull_up"], rationale: "源数据+CF", englishName: "Ring Pull Up",
          englishIntro: "A pull-up performed while holding rings", englishSteps: "Stand under the rings, hold them, and hang; bend the arms to pull the chest toward the rings, then lower under control while keeping the torso stable",
          englishKeyPoints: "Practice supinated-grip variations to strengthen the wrists and prepare for muscle-ups", englishScaling: "Raise the rings to make it easier / strict pull-up"),
        s("ring_dip", "吊环臂屈伸", "gym_m09", .l3, "上肢推(过头)", "次数",
          intro: "在吊环上完成的臂屈伸", steps: "支撑于吊环、手臂伸直，屈肘下降至肩低于肘，再推起回到支撑位", keyPoints: "能连续完成 20 次以上可加负重提升难度",
          scaling: "脚辅助吊环臂屈伸 / 双杠臂屈伸", prereqs: ["bar_dip"], rationale: "源数据+CF", englishName: "Ring Dip",
          englishIntro: "A dip performed on rings", englishSteps: "Support yourself on the rings with arms straight; bend the elbows and lower until the shoulders are below the elbows, then press back up to a stable support",
          englishKeyPoints: "Once you can perform more than 20 consecutive reps, add load to increase difficulty", englishScaling: "Foot-assisted ring dip / bar dip"),
        s("turkish_get_up", "土耳其起立", "gym_m07", .l3, "复合全身", "次数",
          intro: "从仰卧到站立全程把壶铃举过头的复合动作", steps: "仰卧单臂举铃过头，依次起身经肘撑、手撑、抬髋、扫腿到弓步起立，再原路返回", keyPoints: "几乎调动全身肌肉；可用壶铃、哑铃或小杠铃",
          scaling: "徒手分解练习 / 减轻负重", prereqs: [], rationale: "CF通用进阶", englishName: "Turkish Get Up",
          englishIntro: "A total-body movement that moves from lying down to standing while holding a kettlebell overhead", englishSteps: "Lie on your back and hold a kettlebell overhead with one arm; move through elbow support, hand support, hip lift, leg sweep, and lunge to stand, then reverse the sequence",
          englishKeyPoints: "Uses nearly the entire body; can be performed with a kettlebell, dumbbell, or small barbell", englishScaling: "Bodyweight step-by-step practice / reduce the load"),
        s("pull_up", "引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "悬垂于单杠将身体拉起的上肢拉力动作", steps: "正握悬垂、手臂伸直；发力拉至下巴过杠，控制下放至完全悬垂", keyPoints: "进阶顺序：跳跃引体向上→等长悬停→标准引体；可用辅助器械或递减组增强力量",
          scaling: "弹力带辅助引体 / 跳跃引体 / 吊环划船", prereqs: ["ring_row"], rationale: "源数据", englishName: "Pull Up",
          englishIntro: "An upper-body pulling movement that raises the body from a hang on a bar", englishSteps: "Hang from the bar with an overhand grip and straight arms; pull until the chin clears the bar, then lower under control to a full hang",
          englishKeyPoints: "Progression: jumping pull-up, isometric holds, then standard pull-up; assistance machines or drop sets can help build strength", englishScaling: "Band-assisted pull-up / jumping pull-up / ring row"),
        s("burpee_pull_up", "波比引体向上", "gym_m07", .l3, "复合全身", "次数",
          intro: "波比跳衔接引体向上的复合动作", steps: "完成一次波比跳，跳起握杠借力拉至下巴过杠，落地进入下一次", keyPoints: "需分别掌握波比跳与引体两个动作",
          scaling: "弹力带辅助引体 / 拆成波比+引体", prereqs: ["burpee", "pull_up"], rationale: "CF通用进阶", englishName: "Burpee Pull Up",
          englishIntro: "A burpee linked directly into a pull-up", englishSteps: "Complete one burpee, jump to grab the bar, use momentum to pull until the chin clears the bar, then land and start the next rep",
          englishKeyPoints: "Requires proficiency in both the burpee and the pull-up", englishScaling: "Band-assisted pull-up / break into burpee + pull-up"),
        s("burpee_box_jump_over", "波比跳箱越过", "gym_m07", .l3, "复合全身", "次数",
          intro: "波比跳衔接越过跳箱", steps: "完成一次波比跳，起身跳上或越过跳箱并从另一侧落地", keyPoints: "顶端无需完全伸直身体；可调整次数与箱高适合各水平",
          scaling: "降低箱高 / 波比+踏箱上步", prereqs: ["burpee", "box_jump"], rationale: "CF通用进阶", englishName: "Burpee Box Jump Over",
          englishIntro: "A burpee followed by moving over a box", englishSteps: "Complete one burpee, stand up, jump onto or over the box, and land on the other side",
          englishKeyPoints: "Full extension at the top is not required; adjust reps and box height for all levels", englishScaling: "Lower the box / burpee + box step-up"),
        s("rope_climb", "爬绳", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "利用腿夹绳与上肢拉力向上攀爬", steps: "双手握绳、用脚夹绳支撑，伸腿—屈臂换手向上攀爬至指定高度，控制下降", keyPoints: "标准绳长约 4.5 米（15 英尺）；动作正确时腿部承力，握力常最先受挑战",
          scaling: "坐姿拉绳起立 / 降低攀爬高度", prereqs: ["pull_up"], rationale: "源数据+CF", englishName: "Rope Climb",
          englishIntro: "A climb using the legs to pinch the rope and the upper body to pull", englishSteps: "Grip the rope with both hands and clamp it with the feet for support; extend the legs, pull with the arms, move the hands up, and climb to the target height, then descend under control",
          englishKeyPoints: "Standard rope height is about 15 ft (4.5 m); with proper technique the legs do most of the work, while grip is often the first limiter", englishScaling: "Seated rope pull to standing / reduce the climb height"),
        s("chest_to_bar_pull_up", "胸触杠引体向上", "gym_m10", .l3, "上肢拉(垂直)", "次数",
          intro: "借摆动将胸部触碰单杠的引体", steps: "弓形—空心摆动蓄力，爆发上拉使锁骨下方胸部触杠，控制下放保持节奏", keyPoints: "需借摆动（kipping）把胸拉到杠；先掌握标准引体再练",
          scaling: "借力引体向上 / 拉到下巴过杠", prereqs: ["kipping_pull_up"], rationale: "源数据", englishName: "Chest To Bar Pull Up",
          englishIntro: "A kipping pull-up where the chest touches the bar", englishSteps: "Cycle an arch-to-hollow swing, then pull explosively until the chest below the collarbone touches the bar; lower under control and keep the rhythm",
          englishKeyPoints: "Requires a kip to pull the chest to the bar; master the standard pull-up first", englishScaling: "Kipping pull-up / pull only to chin-over-bar"),
        s("toes_to_bar", "脚触杠", "gym_m01", .l3, "核心", "次数",
          intro: "悬垂将双脚抬起触碰单杠的核心动作", steps: "悬垂于单杠，肩部主动、核心收紧；摆动把双脚同时上抬触杠，控制下放回弧形位", keyPoints: nil,
          scaling: "膝触肘 / 悬垂屈膝抬腿", prereqs: ["knees_to_elbows"], rationale: "源数据+CF", englishName: "Toes To Bar",
          englishIntro: "A core movement that raises both feet to touch the pull-up bar while hanging", englishSteps: "Hang from the bar with active shoulders and a braced core; swing and raise both feet together to touch the bar, then lower under control back to the arch position",
          englishKeyPoints: nil, englishScaling: "Knees to elbows / hanging knee raise"),
        s("box_jump_over", "跳箱越过", "gym_m05", .l3, "跳跃", "次数",
          intro: "跳上并越过跳箱落到另一侧", steps: "屈膝摆臂跳上或直接越过跳箱，从另一侧落地，转身重复", keyPoints: "顶端无需完全锁定膝髋",
          scaling: "降低箱高 / 跳上再下", prereqs: ["box_jump"], rationale: "CF通用进阶", englishName: "Box Jump Over",
          englishIntro: "A jump onto and over a box to land on the other side", englishSteps: "Bend the knees and swing the arms to jump onto or directly over the box; land on the other side, turn, and repeat",
          englishKeyPoints: "Full hip and knee lockout at the top is not required", englishScaling: "Lower the box / jump up then step down"),
        s("l_sit_pull_up", "L坐引体向上", "gym_m11", .l4, "上肢拉(垂直)/核心", "静力时长",
          intro: "保持 L 坐姿同时完成引体向上", steps: "悬垂抬腿成 L 形，保持双腿水平拉至下巴过杠，控制下放，全程缓慢可控", keyPoints: "先掌握标准引体与各位置 L 坐；节奏慢、全程可控，勿借惯性",
          scaling: "屈腿引体保持 / 严格引体向上", prereqs: ["strict_pull_up"], rationale: "源数据", englishName: "L Sit Pull Up",
          englishIntro: "A pull-up performed while holding an L-sit position", englishSteps: "Hang from the bar and raise the legs into an L shape; hold the legs level as you pull until the chin clears the bar, then lower under control with a slow tempo",
          englishKeyPoints: "Master strict pull-ups and L-sit positions first; move slowly and under control without using momentum", englishScaling: "Bent-leg pull-up hold / strict pull-up"),
        s("strict_handstand_push_up", "严格倒立俯卧撑", "gym_m09", .l4, "上肢推(过头)", "次数",
          intro: "不借摆动的靠墙倒立俯卧撑", steps: "靠墙倒立、身体收紧，控制屈肘下降至头顶触地，再纯靠上肢推起伸直", keyPoints: "纯靠力量、不借摆动，难度高于借力版本",
          scaling: "倒立俯卧撑 / 垫高减幅", prereqs: ["handstand_push_up"], rationale: "源数据", englishName: "Strict Handstand Push Up",
          englishIntro: "A wall-supported handstand push-up performed without a kip", englishSteps: "Kick up to a wall-supported handstand and brace the body; bend the elbows under control until the top of the head touches the floor, then press up with upper-body strength only",
          englishKeyPoints: "Strict strength only, no kip; more difficult than the kipping version", englishScaling: "Handstand push-up / elevate the surface to reduce range"),
        s("strict_ring_dip", "严格吊环臂屈伸", "gym_m09", .l4, "上肢推(过头)", "次数",
          intro: "不借摆动的吊环臂屈伸", steps: "支撑于环、颈长身空，肩前倾下降至肩低于肘，再撑回稳定支撑位", keyPoints: nil,
          scaling: "吊环臂屈伸 / 脚辅助", prereqs: ["ring_dip"], rationale: "源数据+CF", englishName: "Strict Ring Dip",
          englishIntro: "A ring dip performed without using momentum", englishSteps: "Support yourself on the rings with a long neck and hollow body; lean the shoulders forward and lower until they pass below the elbows, then press back to a stable support",
          englishKeyPoints: nil, englishScaling: "Ring dip / foot-assisted"),
        s("handstand_push_up", "倒立俯卧撑", "gym_m09", .l4, "上肢推(过头)", "次数",
          intro: "倒立姿势下完成的过头推力动作", steps: "靠墙倒立、身体收紧；屈肘下降至头顶触地，再推起至手臂完全伸直", keyPoints: "进阶：先掌握标准俯卧撑、靠墙倒立保持 60 秒、屈体俯卧撑、半程与控制下落，再做完整动作",
          scaling: "垫高减幅 / 屈体俯卧撑 / 箱上HSPU", prereqs: ["push_up", "shoulder_press"], rationale: "源数据+CF", englishName: "Handstand Push Up",
          englishIntro: "An overhead pressing movement performed in a handstand position", englishSteps: "Kick up to a wall-supported handstand and brace the body; bend the elbows until the top of the head touches the floor, then press up until the arms are fully straight",
          englishKeyPoints: "Progression: standard push-ups, 60-second wall handstand hold, pike push-ups, partial range, controlled negatives, then the full movement", englishScaling: "Elevate to reduce range / pike push-up / box HSPU"),
        s("pistol_squat", "手枪深蹲", "gym_m06", .l4, "弓步单腿", "次数",
          intro: "单腿完成的全幅深蹲", steps: "单腿支撑、另一腿前伸离地，控制膝盖方向下蹲至最低点，再蹬地站起", keyPoints: "高难动作，可借单杠辅助、抬高后腿或部分幅度等方式简化",
          scaling: "箱上单腿蹲 / 辅助单腿蹲", prereqs: ["air_squat"], rationale: "源数据+CF", englishName: "Pistol Squat",
          englishIntro: "A full-range single-leg squat", englishSteps: "Stand on one leg with the other leg extended forward off the floor; control the knee position as you squat to the bottom, then drive through the floor to stand",
          englishKeyPoints: "Advanced movement; scale with bar assistance, an elevated non-working leg, or partial range of motion", englishScaling: "Box single-leg squat / assisted single-leg squat"),
        s("strict_muscle_up", "严格双力臂", "gym_m10", .l5, "上肢拉(垂直)", "次数",
          intro: "不借摆动的吊环双力臂", steps: "假握悬垂，纯靠上拉使肩过环，前倾过渡后撑起至手臂锁定", keyPoints: "纯靠力量、不借摆动，难度高",
          scaling: "吊环双力臂 / 弹力带辅助", prereqs: ["ring_muscle_up", "strict_ring_dip"], rationale: "源数据+CF", englishName: "Strict Muscle Up",
          englishIntro: "A ring muscle-up performed without a kip", englishSteps: "Hang from the rings in a false grip; pull strictly until the shoulders pass above the rings, lean forward through the transition, and press to locked-out support",
          englishKeyPoints: "Strict strength only, no kip; high difficulty", englishScaling: "Ring muscle-up / band-assisted"),
        s("handstand_walk", "倒立行走", "gym_m09", .l5, "上肢推(过头)", "距离",
          intro: "倒立姿势下用手向前行走", steps: "稳定倒立、重心在手指，肩部主动撑起，交替移动双手向前行走", keyPoints: nil,
          scaling: "靠墙倒立漂浮 / 熊爬", prereqs: ["handstand"], rationale: "源数据+CF", englishName: "Handstand Walk",
          englishIntro: "Forward travel on the hands while in a handstand", englishSteps: "Hold a stable handstand with weight balanced through the fingers; actively press through the shoulders and move the hands forward one at a time",
          englishKeyPoints: nil, englishScaling: "Wall handstand float / bear crawl"),
        s("kipping_bar_muscle_up", "借力单杠双力臂", "gym_m10", .l5, "上肢拉(垂直)", "次数",
          intro: "借摆动连续完成的单杠双力臂", steps: "弓形摆动蓄力上拉使胸过杠，双肩同步过渡撑起至手臂伸直", keyPoints: "先掌握标准引体、摆动引体、胸触杠与双杠臂屈伸；双肩双肘须同步，勿单侧过杠以免受伤",
          scaling: "弹力带辅助 / 高位胸触杠+翻杠", prereqs: ["chest_to_bar_pull_up", "bar_dip", "toes_to_bar"], rationale: "源数据", englishName: "Kipping Bar Muscle Up",
          englishIntro: "A bar muscle-up performed continuously with a kip", englishSteps: "Use an arch swing to build momentum, pull until the chest rises above the bar, transition both shoulders over the bar together, and press to straight arms",
          englishKeyPoints: "First master strict pull-ups, kipping pull-ups, chest-to-bar pull-ups, and bar dips; keep both shoulders and elbows moving together and avoid one-sided transitions to reduce injury risk", englishScaling: "Band-assisted / high chest-to-bar + bar roll-over"),
        s("bar_muscle_up", "单杠双力臂", "gym_m10", .l5, "上肢拉(垂直)", "次数",
          intro: "在单杠上由引体过渡到撑起的高难动作", steps: "弓形摆动蓄力，爆发上拉使胸过杠并翻转过渡，撑起至手臂伸直", keyPoints: "高难动作，建议先掌握准备动作；肩关节损伤或慢性病者慎做",
          scaling: "弹力带辅助双力臂 / 高位胸触杠+翻杠过渡", prereqs: ["strict_pull_up", "chest_to_bar_pull_up", "bar_dip", "toes_to_bar"], rationale: "源数据+CF", englishName: "Bar Muscle Up",
          englishIntro: "An advanced movement on the bar that transitions from a pull-up to a support", englishSteps: "Use an arch swing, pull explosively until the chest passes the bar, roll through the transition, and press to straight arms",
          englishKeyPoints: "Advanced movement; master the prerequisite skills first. Use caution with shoulder injuries or chronic conditions", englishScaling: "Band-assisted muscle-up / high chest-to-bar + bar roll-over transition"),
        s("ring_handstand_push_up", "吊环倒立俯卧撑", "gym_m09", .l5, "上肢推(过头)", "次数",
          intro: "在吊环上完成的倒立俯卧撑，高难度", steps: "吊环倒立、身体核心收紧，控制屈肘下降头近地，再推起伸直，尽量保持环稳定", keyPoints: "高难，需强肩部稳定与核心控制，建议在教练指导下训练",
          scaling: "严格倒立俯卧撑 / 垫高减幅", prereqs: ["strict_handstand_push_up"], rationale: "CF通用进阶", englishName: "Ring Handstand Push Up",
          englishIntro: "A high-skill handstand push-up performed on rings", englishSteps: "Kick into a ring handstand, brace the core, lower under control until the head is near the floor, then press back to straight arms while keeping the rings stable",
          englishKeyPoints: "High difficulty; requires strong shoulder stability and core control. Train under coach supervision", englishScaling: "Strict handstand push-up / elevate to reduce range"),
        s("ring_muscle_up", "吊环双力臂", "gym_m10", .l5, "上肢拉(垂直)", "次数",
          intro: "在吊环上由引体过渡到臂屈伸的高难动作", steps: "假握悬垂摆动，爆发上拉、快速过渡使肩过环，撑起至手臂锁定", keyPoints: "高难动作，需良好力量、速度与协调，不适合初学者",
          scaling: "弹力带辅助双力臂 / 拆成引体+吊环臂屈伸+过渡", prereqs: ["strict_pull_up", "ring_dip"], rationale: "源数据+CF", englishName: "Ring Muscle Up",
          englishIntro: "An advanced ring movement that transitions from a pull-up into a dip", englishSteps: "Hang from the rings in a false grip and kip; pull explosively, transition quickly until the shoulders pass the rings, then press to locked-out support",
          englishKeyPoints: "Advanced movement requiring strength, speed, and coordination; not suitable for beginners", englishScaling: "Band-assisted muscle-up / break into pull-up + ring dip + transition"),
        s("back_flip", "后空翻", "gym_m05", .l5, "跳跃", "次数",
          intro: "原地向后翻转的高风险技巧动作", steps: "屈膝摆臂蹬地起跳并向后甩头团身翻转，看到地面后展体、屈膝脚尖落地。建议在保护下练习", keyPoints: "高风险技巧动作，建议在保护下练习",
          scaling: "保护下练习 / 后滚翻过渡", prereqs: ["forward_roll"], rationale: "源数据+CF", englishName: "Back Flip",
          englishIntro: "A high-risk skill that rotates backward from a standing jump", englishSteps: "Dip and swing the arms to jump, throw the head and tuck to rotate backward, then open when you see the floor and land on the balls of the feet with bent knees. Practice with a spotter",
          englishKeyPoints: "High-risk skill; practice with a spotter", englishScaling: "Practice with a spotter / backward roll progression"),
        s("legless_rope_climb", "无腿爬绳", "gym_m10", .l5, "上肢拉(垂直)", "次数",
          intro: "不借腿、仅用手臂攀爬绳索", steps: "双臂完全悬垂，用手拉手或摆动方式仅靠上肢交替向上攀爬，握力要强", keyPoints: "强握力是关键；手拉手最快但易疲劳，疲劳后改摆动式",
          scaling: "爬绳 / 降低攀爬高度", prereqs: ["rope_climb", "strict_pull_up"], rationale: "源数据+CF", englishName: "Legless Rope Climb",
          englishIntro: "A rope climb performed without using the legs", englishSteps: "Hang fully from the rope; climb using either hand-over-hand pulls or a kip, relying only on the upper body and maintaining strong grip",
          englishKeyPoints: "Strong grip is key; hand-over-hand is fastest but fatiguing, so switch to a kipping style as fatigue builds", englishScaling: "Rope climb (with legs) / reduce the climb height"),
        s("burpee_bar_muscle_up", "波比单杠双力臂", "gym_m07", .l5, "复合全身", "次数",
          intro: "波比跳衔接单杠双力臂", steps: "完成一次波比跳，跳起握杠爆发上拉过杠，撑起至手臂伸直", keyPoints: nil,
          scaling: "弹力带辅助双力臂 / 拆成波比+双力臂", prereqs: ["bar_muscle_up", "burpee"], rationale: "CF通用进阶", englishName: "Burpee Bar Muscle Up",
          englishIntro: "A burpee linked directly into a bar muscle-up", englishSteps: "Complete one burpee, jump to the bar, pull explosively over the bar, and press to straight arms",
          englishKeyPoints: nil, englishScaling: "Band-assisted muscle-up / break into burpee + muscle-up"),
        s("burpee_muscle_up", "波比双力臂", "gym_m07", .l5, "复合全身", "次数",
          intro: "波比跳衔接吊环双力臂", steps: "完成一次波比跳，跳上吊环借摆动过渡撑起至手臂锁定", keyPoints: "需分别掌握波比跳与吊环双力臂",
          scaling: "弹力带辅助双力臂 / 拆成波比+吊环双力臂", prereqs: ["ring_muscle_up", "burpee"], rationale: "CF通用进阶", englishName: "Burpee Muscle Up",
          englishIntro: "A burpee linked directly into a ring muscle-up", englishSteps: "Complete one burpee, jump to the rings, use a kip to transition, and press to locked-out support",
          englishKeyPoints: "Requires proficiency in both the burpee and the ring muscle-up", englishScaling: "Band-assisted muscle-up / break into burpee + ring muscle-up")
    ]

    // MARK: 举重 Weightlifting (67)

    static let weightlifting = SkillCategoryDefinition(
        id: "weightlifting",
        name: "举重",
        englishName: "Weightlifting",
        icon: "figure.strengthtraining.traditional",
        color: Color(hex: "#5BE88F"),
        subcategories: [
            SkillSubcategoryDefinition(id: "wl_m01", name: "搬运行走", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m02", name: "髋铰链", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m03", name: "上肢拉(水平)", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m04", name: "深蹲", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m05", name: "上肢推(过头)", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m06", name: "上肢拉(水平)/核心", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m07", name: "上肢推(水平)", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m08", name: "奥举", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m09", name: "复合全身", categoryId: "weightlifting"),
            SkillSubcategoryDefinition(id: "wl_m10", name: "弓步单腿", categoryId: "weightlifting"),
        ],
        skills: weightliftingSkills
    )

    private static let weightliftingSkills: [SkillDefinition] = [
        s("farmers_walk", "农夫行走", "wl_m01", .l1, "搬运行走", "距离",
          intro: "双手负重行走的搬运动作", steps: "双手各持重物，收紧核心挺直身体，迈小而快的步伐走完指定距离", keyPoints: "勿直接把重物摔在地上，控制放下",
          scaling: "减重 / 缩短距离", prereqs: [], rationale: "基础动作", englishName: "Farmers Walk",
          englishIntro: "A loaded carry performed while walking with weights in both hands", englishSteps: "Hold a weight in each hand, brace the core, keep the body tall, and take short, quick steps to cover the prescribed distance",
          englishKeyPoints: "Do not drop the weights directly on the floor; set them down under control", englishScaling: "Reduce the load / shorten the distance"),
        s("double_kettlebell_deadlift", "双壶铃硬拉", "wl_m02", .l1, "髋铰链", "次数",
          intro: "双手各持壶铃从地面拉起", steps: "双壶铃置脚两侧、背部中立，伸髋伸膝拉起站直，再控制放回", keyPoints: nil,
          scaling: "减重 / 单壶铃硬拉", prereqs: ["deadlift"], rationale: "CF通用进阶", englishName: "Double Kettlebell Deadlift",
          englishIntro: "A deadlift from the floor with one kettlebell in each hand", englishSteps: "Place the kettlebells at the sides of the feet; keep the back neutral, extend the hips and knees to stand, then lower them under control",
          englishKeyPoints: nil, englishScaling: "Reduce the load / single-kettlebell deadlift"),
        s("two_arm_kettlebell_row", "双臂壶铃划船", "wl_m03", .l1, "上肢拉(水平)", "次数",
          intro: "双手持壶铃俯身划船", steps: "双手持壶铃屈髋、背中立，把壶铃拉向躯干收肩胛，控制放回", keyPoints: nil,
          scaling: "减重 / 减小幅度", prereqs: [], rationale: "基础动作", englishName: "Two Arm Kettlebell Row",
          englishIntro: "A bent-over row performed with a kettlebell in each hand", englishSteps: "Hold a kettlebell in each hand, hinge at the hips with a neutral back, pull the kettlebells toward the torso by squeezing the shoulder blades, then lower under control",
          englishKeyPoints: nil, englishScaling: "Reduce the load / reduce the range of motion"),
        s("dumbbell_squat", "哑铃深蹲", "wl_m04", .l1, "深蹲", "次数",
          intro: "手持哑铃完成的深蹲", steps: "哑铃置肩、体侧或前架位，核心收紧下蹲后站起", keyPoints: nil,
          scaling: "减重 / 徒手深蹲", prereqs: ["air_squat", "goblet_squat"], rationale: "CF通用进阶", englishName: "Dumbbell Squat",
          englishIntro: "A squat performed while holding dumbbells", englishSteps: "Hold the dumbbells at the shoulders, at the sides, or in the front rack; brace the core, squat down, then stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / air squat"),
        s("dumbbell_deadlift", "哑铃硬拉", "wl_m02", .l1, "髋铰链", "次数",
          intro: "用哑铃完成的硬拉", steps: "双哑铃置身侧、屈膝不屈背，下放至哑铃近地，再伸髋伸膝站直", keyPoints: "屈膝不屈背、手臂全程伸直；无杠铃时的理想替代",
          scaling: "减重 / 减小幅度", prereqs: ["deadlift"], rationale: "CF通用进阶", englishName: "Dumbbell Deadlift",
          englishIntro: "A deadlift performed with dumbbells", englishSteps: "Place the dumbbells at your sides; bend the knees without rounding the back, lower until the dumbbells are near the floor, then extend the hips and knees to stand",
          englishKeyPoints: "Bend the knees without rounding the back and keep the arms straight throughout; an ideal substitute when a barbell is unavailable", englishScaling: "Reduce the load / reduce the range of motion"),
        s("kettlebell_sumo_deadlift", "壶铃相扑硬拉", "wl_m02", .l1, "髋铰链", "次数",
          intro: "宽站距用壶铃完成的硬拉", steps: "宽站距窄握壶铃、臀低胸挺，伸髋伸膝拉起站直，再控制放回", keyPoints: nil,
          scaling: "减重 / 减小幅度", prereqs: ["deadlift", "sumo_deadlift"], rationale: "CF通用进阶", englishName: "Kettlebell Sumo Deadlift",
          englishIntro: "A wide-stance deadlift performed with a kettlebell", englishSteps: "Take a wide stance and narrow grip on the kettlebell with hips low and chest up; extend the hips and knees to stand, then lower under control",
          englishKeyPoints: nil, englishScaling: "Reduce the load / reduce the range of motion"),
        s("sumo_deadlift", "相扑硬拉", "wl_m02", .l1, "髋铰链", "次数",
          intro: "宽站距完成的硬拉", steps: "宽站距窄握、臀低胸挺，伸髋伸膝拉起至站直，再控制放回", keyPoints: "对许多人比常规硬拉更友好的变式",
          scaling: "减重 / 常规硬拉", prereqs: ["deadlift"], rationale: "CF通用进阶", englishName: "Sumo Deadlift",
          englishIntro: "A deadlift performed with a wide stance", englishSteps: "Take a wide stance and narrow grip with hips low and chest up; extend the hips and knees to stand tall, then lower under control",
          englishKeyPoints: "For many athletes, this is a more accessible variation than the conventional deadlift", englishScaling: "Reduce the load / conventional deadlift"),
        s("goblet_squat", "高脚杯深蹲", "wl_m04", .l1, "深蹲", "次数",
          intro: "胸前抱单只哑铃或壶铃的深蹲", steps: "双手抱铃于胸前，屈髋屈膝下蹲至最低点，膝随脚尖外展，蹬地站直", keyPoints: "胸前抱铃可减轻下背压力，适合肩部活动受限者",
          scaling: "减重 / 徒手深蹲", prereqs: ["air_squat"], rationale: "CF通用进阶", englishName: "Goblet Squat",
          englishIntro: "A squat holding one dumbbell or kettlebell at the chest", englishSteps: "Hold the bell at the chest with both hands; squat to the bottom with the knees tracking over the toes, then drive through the floor to stand",
          englishKeyPoints: "Holding the load at the chest reduces low-back stress and suits athletes with limited shoulder mobility", englishScaling: "Reduce the load / air squat"),
        s("alternating_kettlebell_shoulder_press", "交替壶铃肩推", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "左右交替的单臂壶铃肩上推举", steps: "双壶铃举至肩侧，一侧推过头另一侧不动，挺胸收腹不晃身，换侧交替", keyPoints: "推举时勿左右晃身、收紧腹部稳定",
          scaling: "减重 / 双手壶铃推举", prereqs: ["shoulder_press"], rationale: "CF通用进阶", englishName: "Alternating Kettlebell Shoulder Press",
          englishIntro: "An alternating single-arm kettlebell overhead press", englishSteps: "Clean both kettlebells to the shoulders; press one overhead while the other stays in place, keep the chest up and abs braced, then alternate sides",
          englishKeyPoints: "Do not sway side to side while pressing; keep the abs braced for stability", englishScaling: "Reduce the load / two-arm kettlebell press"),
        s("renegade_row", "俯撑哑铃划船", "wl_m06", .l2, "上肢拉(水平)/核心", "次数",
          intro: "俯撑姿势下单臂交替划船", steps: "双手撑哑铃成俯撑，一手撑地另一手把哑铃拉至腰侧，核心稳定交替进行", keyPoints: "需大量稳定力量，能强化腹部与核心；在平稳表面进行",
          scaling: "膝盖俯撑 / 减重", prereqs: [], rationale: "CF通用进阶", englishName: "Renegade Row",
          englishIntro: "An alternating one-arm row from a plank position", englishSteps: "Assume a push-up position with hands on the dumbbells; support with one hand while rowing the other dumbbell to the side of the waist, keeping the core stable, then alternate",
          englishKeyPoints: "Requires significant stability and strengthens the abs and core; perform on a stable surface", englishScaling: "Knees-down plank / reduce the load"),
        s("push_press", "借力推举", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "借腿部下蹲发力把杠铃推举过头", steps: "前架持杠微屈膝下蹲，爆发蹬地借力把杠铃推举过头锁定，落回肩部", keyPoints: nil,
          scaling: "减重 / 肩上推举", prereqs: ["shoulder_press"], rationale: "CF通用进阶", englishName: "Push Press",
          englishIntro: "An overhead press that uses a shallow dip and leg drive", englishSteps: "Hold the bar in the front rack, dip slightly by bending the knees, then drive explosively through the floor to press the bar overhead to lockout before returning it to the shoulders",
          englishKeyPoints: nil, englishScaling: "Reduce the load / shoulder press"),
        s("front_squat", "前蹲", "wl_m04", .l2, "深蹲", "次数",
          intro: "杠铃置于前架位的深蹲", steps: "前架持杠、肘部抬高，屈髋屈膝下蹲至大腿过平行，蹬地站直", keyPoints: "前架位能用更小重量激活更多股四头肌，适合肩部活动受限者",
          scaling: "减重 / 高脚杯深蹲", prereqs: ["air_squat", "back_squat"], rationale: "CF通用进阶", englishName: "Front Squat",
          englishIntro: "A squat with the barbell in the front rack", englishSteps: "Hold the bar in the front rack with elbows high; squat until the thighs pass below parallel, then drive through the floor to stand",
          englishKeyPoints: "The front rack can recruit the quadriceps more with less load and may suit athletes with limited shoulder mobility", englishScaling: "Reduce the load / goblet squat"),
        s("one_arm_kettlebell_press", "单臂壶铃推举", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "单臂把壶铃从肩推举至过头", steps: "单臂壶铃置肩，肋骨下沉核心收紧，推举过头锁定，避免侧倾后仰", keyPoints: nil,
          scaling: "减重 / 双手推举", prereqs: ["shoulder_press"], rationale: "CF通用进阶", englishName: "One Arm Kettlebell Press",
          englishIntro: "A single-arm kettlebell press from the shoulder to overhead", englishSteps: "Rack the kettlebell at one shoulder; keep the ribs down and core tight, press overhead to lockout, and avoid leaning sideways or backward",
          englishKeyPoints: nil, englishScaling: "Reduce the load / two-arm press"),
        s("bench_press", "卧推", "wl_m07", .l2, "上肢推(水平)", "次数",
          intro: "仰卧将杠铃推离胸部的上肢推力动作", steps: "仰卧收紧肩胛、双脚踩实，握距略宽于肩；吸气下放杠铃至胸，再推起至手臂伸直", keyPoints: "建议有同伴保护；下背自然拱不过度、勿让杠铃弹胸；腰/颈椎创伤或慢性病者慎做",
          scaling: "减重 / 俯卧撑", prereqs: ["push_up"], rationale: "CF通用进阶", englishName: "Bench Press",
          englishIntro: "An upper-body pushing movement that presses a barbell away from the chest while lying supine", englishSteps: "Lie on the bench, retract the shoulder blades, and plant the feet; grip slightly wider than shoulder-width, inhale and lower the bar to the chest, then press to straight arms",
          englishKeyPoints: "Use a spotter when possible; keep a natural, not excessive, lower-back arch and do not bounce the bar off the chest. Use caution with lumbar or cervical spine trauma or chronic conditions", englishScaling: "Reduce the load / push-up"),
        s("back_squat", "后蹲", "wl_m04", .l2, "深蹲", "次数",
          intro: "杠铃置于后背的深蹲", steps: "杠铃置斜方肌、双脚与肩同宽，屈髋屈膝下蹲至大腿过平行，背部挺直蹬地站直", keyPoints: "不建议初学者无教练指导进行；膝外展、下背中立、勿让脚尖超过膝、勿抬头；腰椎间盘突出或膝关节疾病复杂者慎做",
          scaling: "减重 / 徒手深蹲", prereqs: ["air_squat"], rationale: "CF通用进阶", englishName: "Back Squat",
          englishIntro: "A squat with the barbell positioned across the upper back", englishSteps: "Place the bar on the traps and set the feet about shoulder-width apart; hinge and bend the knees to squat below parallel, keep the back tight, and drive through the floor to stand",
          englishKeyPoints: "Beginners should not perform this without coach guidance; keep the knees tracking out, lower back neutral, avoid forcing the knees past the toes, and do not crank the head up. Use caution with lumbar disc herniation or complex knee conditions", englishScaling: "Reduce the load / air squat"),
        s("dumbbell_push_press", "哑铃借力推举", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "借腿部发力把哑铃推举过头", steps: "双哑铃置肩、微屈膝下蹲，蹬地借力将哑铃推举过头锁定，落回肩部", keyPoints: nil,
          scaling: "减重 / 哑铃推举", prereqs: ["dumbbell_press"], rationale: "CF通用进阶", englishName: "Dumbbell Push Press",
          englishIntro: "An overhead dumbbell press assisted by leg drive", englishSteps: "Hold the dumbbells at the shoulders, dip slightly, then drive with the legs to press the dumbbells overhead to lockout before returning them to the shoulders",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell press"),
        s("dumbbell_power_clean", "哑铃力量翻站", "wl_m08", .l2, "奥举", "次数",
          intro: "双哑铃翻至肩、不进入深蹲", steps: "哑铃从地面或低位爆发上拉，在高位屈臂接至肩，背部中立", keyPoints: nil,
          scaling: "减重 / 哑铃翻站", prereqs: ["dumbbell_clean"], rationale: "CF通用进阶", englishName: "Dumbbell Power Clean",
          englishIntro: "A dumbbell clean received at the shoulders without a full squat", englishSteps: "Pull the dumbbells explosively from the floor or low position, bend the arms at the top, and receive them at the shoulders while keeping the back neutral",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell clean"),
        s("dumbbell_press", "哑铃推举", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "站姿将哑铃严格推举过头", steps: "双哑铃举至头侧、肘约 90 度，不借腿力伸肘把哑铃推过头，控制回落", keyPoints: nil,
          scaling: "减重 / 肩上推举", prereqs: ["shoulder_press"], rationale: "CF通用进阶", englishName: "Dumbbell Press",
          englishIntro: "A strict standing dumbbell press to overhead", englishSteps: "Hold the dumbbells beside the head with elbows about 90 degrees; without leg drive, extend the elbows to press overhead, then lower under control",
          englishKeyPoints: nil, englishScaling: "Reduce the load / shoulder press"),
        s("dumbbell_burpee_deadlift", "哑铃波比硬拉", "wl_m09", .l2, "复合全身", "次数",
          intro: "手持哑铃完成的波比硬拉", steps: "持哑铃俯身下蹲、双腿后撑成俯撑做俯卧撑，跳回起身把哑铃拉至肩高站直", keyPoints: "勿用过重哑铃，否则动作易变形受伤",
          scaling: "减重 / 拆成波比+哑铃硬拉", prereqs: ["burpee", "dumbbell_deadlift"], rationale: "CF通用进阶", englishName: "Dumbbell Burpee Deadlift",
          englishIntro: "A burpee-deadlift combination performed while holding dumbbells", englishSteps: "Holding the dumbbells, squat and place them on the floor, jump the legs back into a push-up, jump back in, then stand and pull the dumbbells up to shoulder height",
          englishKeyPoints: "Do not choose dumbbells that are too heavy, or the movement can break down and increase injury risk", englishScaling: "Reduce the load / break into burpee + dumbbell deadlift"),
        s("dumbbell_clean", "哑铃翻站", "wl_m08", .l2, "奥举", "次数",
          intro: "双哑铃从地面翻至肩的动作", steps: "哑铃落地屈髋,爆发伸髋伸膝上拉，屈臂在肩前接住，站直", keyPoints: nil,
          scaling: "减重 / 哑铃高拉至肩", prereqs: ["deadlift", "kettlebell_swing"], rationale: "CF通用进阶", englishName: "Dumbbell Clean",
          englishIntro: "A clean that brings two dumbbells from the floor to the shoulders", englishSteps: "Place the dumbbells on the floor, hinge at the hips, explosively extend the hips and knees to pull, bend the arms, receive the dumbbells at the shoulders, and stand tall",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell high pull to the shoulder"),
        s("wall_ball", "墙球", "wl_m09", .l2, "复合全身", "次数",
          intro: "深蹲后将药球抛向墙面目标的动作", steps: "高脚杯抱球下蹲至髋低于膝，蹬地起身借力将球抛向墙面目标，接住落球顺势下蹲", keyPoints: "选择适合自己的球重，下蹲深度可比杠铃深蹲更低",
          scaling: "减轻球重 / 降低目标高度 / 拆成深蹲+推举", prereqs: ["goblet_squat", "push_press"], rationale: "CF通用进阶", englishName: "Wall Ball",
          englishIntro: "A squat followed by throwing a medicine ball to a wall target", englishSteps: "Hold the ball in a goblet position, squat until the hip crease is below the knees, drive up, and use the legs to throw the ball to the wall target; catch it and descend into the next squat",
          englishKeyPoints: "Choose an appropriate ball weight; squat depth can be lower than in a barbell squat", englishScaling: "Reduce the ball weight / lower the target / break into squat + press"),
        s("kettlebell_swing", "壶铃摆动", "wl_m02", .l2, "髋铰链", "次数",
          intro: "靠髋部发力将壶铃摆至胸高的全身动作", steps: "屈髋后坐握壶铃，爆发伸髋把壶铃摆到胸高，手臂放松；顺势回摆至两腿间连续进行", keyPoints: "初学先用较轻壶铃掌握动作再加重",
          scaling: "减轻壶铃 / 俄式摆动（摆至胸高）", prereqs: ["deadlift"], rationale: "CF通用进阶", englishName: "Kettlebell Swing",
          englishIntro: "A full-body hip-driven swing that brings the kettlebell to chest height", englishSteps: "Hinge back and grip the kettlebell; explosively extend the hips to swing it to chest height with relaxed arms, then let it swing back between the legs and continue",
          englishKeyPoints: "Beginners should learn the movement with a lighter kettlebell before increasing load", englishScaling: "Reduce the kettlebell weight / Russian swing (to chest height)"),
        s("kettlebell_high_pull", "壶铃高拉", "wl_m02", .l2, "髋铰链", "次数",
          intro: "壶铃高拉至肩部的爆发动作", steps: "壶铃置两脚间屈髋握住，伸髋伸膝同时把壶铃上拉至肩、肘抬高，控制回位", keyPoints: nil,
          scaling: "减重 / 壶铃摆动", prereqs: ["kettlebell_swing"], rationale: "CF通用进阶", englishName: "Kettlebell High Pull",
          englishIntro: "An explosive kettlebell pull to shoulder height", englishSteps: "Place the kettlebell between the feet, hinge and grip it, then extend the hips and knees while pulling the kettlebell up to shoulder height with a high elbow; control it back down",
          englishKeyPoints: nil, englishScaling: "Reduce the load / kettlebell swing"),
        s("kettlebell_goblet_thruster", "壶铃高脚杯深蹲推举", "wl_m09", .l2, "复合全身", "次数",
          intro: "壶铃高脚杯深蹲接推举过头", steps: "胸前抱壶铃下蹲至大腿过平行，蹬地起身借力把壶铃推举过头锁定", keyPoints: nil,
          scaling: "减重 / 拆成高脚杯深蹲+推举", prereqs: ["goblet_squat", "push_press"], rationale: "CF通用进阶", englishName: "Kettlebell Goblet Thruster",
          englishIntro: "A goblet squat directly into an overhead press with a kettlebell", englishSteps: "Hold the kettlebell at the chest, squat below parallel, then drive up and use the legs to press the kettlebell overhead to lockout",
          englishKeyPoints: nil, englishScaling: "Reduce the load / break into goblet squat + press"),
        s("stiff_legged_deadlift", "直腿硬拉", "wl_m02", .l2, "髋铰链", "次数",
          intro: "保持腿近伸直、屈髋的硬拉", steps: "双手正握杠铃，腿近伸直屈髋下放至腘绳肌拉伸极限，收紧后链拉起站直", keyPoints: "保持腿近伸直、感受腘绳肌拉伸，看向上方、肩后收以防弓背",
          scaling: "减重 / 减小幅度", prereqs: ["deadlift"], rationale: "CF通用进阶", englishName: "Stiff Legged Deadlift",
          englishIntro: "A hip-hinge deadlift with the legs kept nearly straight", englishSteps: "Hold the barbell with a double overhand grip; keep the legs nearly straight, hinge until the hamstrings reach their end-range stretch, then engage the posterior chain to stand",
          englishKeyPoints: "Keep the legs nearly straight and feel the hamstring stretch; look slightly upward and keep the shoulders back to avoid rounding", englishScaling: "Reduce the load / reduce the range of motion"),
        s("sumo_deadlift_high_pull", "相扑硬拉高拉", "wl_m02", .l2, "髋铰链", "次数",
          intro: "宽站距硬拉接高拉至下巴的复合动作", steps: "宽站距窄握，伸髋伸膝拉起，过膝后抬肘把杠铃上拉至下巴，控制回放", keyPoints: nil,
          scaling: "减重 / 相扑硬拉", prereqs: ["sumo_deadlift"], rationale: "CF通用进阶", englishName: "Sumo Deadlift High Pull",
          englishIntro: "A wide-stance deadlift followed by a high pull to the chin", englishSteps: "Take a wide stance and narrow grip; extend the hips and knees to lift, then once the bar passes the knees, raise the elbows and pull the bar to the chin; lower under control",
          englishKeyPoints: nil, englishScaling: "Reduce the load / sumo deadlift"),
        s("deadlift", "硬拉", "wl_m02", .l2, "髋铰链", "次数",
          intro: "将杠铃从地面拉起至站直的基础力量动作", steps: "杠铃贴小腿、背部挺直，蹬地伸髋伸膝拉起至站直，再屈髋屈膝控制放回", keyPoints: "源自力量举，训练初期数月不建议进行；下背保持中立、勿弓背，重量勿压在手臂和肩上",
          scaling: "减重 / 架上硬拉（垫高起拉）", prereqs: [], rationale: "基础动作", englishName: "Deadlift",
          englishIntro: "A foundational strength movement that lifts a barbell from the floor to standing", englishSteps: "Set the bar close to the shins with the back flat; drive through the floor, extend the hips and knees to stand, then hinge and bend the knees to lower under control",
          englishKeyPoints: "Originates from powerlifting; avoid heavy deadlifts during the first few months of training. Keep the lower back neutral, do not round, and do not let the load hang from the arms and shoulders", englishScaling: "Reduce the load / rack pull (elevated start)"),
        s("shoulder_press", "肩上推举", "wl_m05", .l2, "上肢推(过头)", "次数",
          intro: "靠上肢力量将杠铃严格推举过头", steps: "前架持杠、核心收紧，不借腿力把杠铃沿垂直路线推举过头锁定，再落回肩", keyPoints: nil,
          scaling: "减重 / 哑铃推举", prereqs: [], rationale: "基础动作", englishName: "Shoulder Press",
          englishIntro: "A strict overhead press driven by upper-body strength", englishSteps: "Hold the bar in the front rack and brace the core; without leg drive, press the bar vertically overhead to lockout, then return it to the shoulders",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell press"),
        s("weighted_lunge", "负重弓步", "wl_m10", .l2, "弓步单腿", "次数",
          intro: "手持或负重完成的弓步", steps: "持重物保持躯干直立，向前或原地下蹲至后膝近地，蹬前脚起身换腿", keyPoints: "可用哑铃、壶铃、杠铃、沙袋等负重",
          scaling: "减重 / 徒手行走弓步", prereqs: ["walking_lunge"], rationale: "CF通用进阶", englishName: "Weighted Lunge",
          englishIntro: "A lunge performed while holding an external load", englishSteps: "Hold the load and keep the torso upright; step forward or stay in place, lower until the back knee is near the floor, then drive through the front foot and switch legs",
          englishKeyPoints: "Can be loaded with dumbbells, kettlebells, a barbell, a sandbag, or similar implements", englishScaling: "Reduce the load / bodyweight walking lunge"),
        s("alternating_dumbbell_snatch", "交替哑铃抓举", "wl_m08", .l3, "奥举", "次数",
          intro: "左右交替的单臂哑铃抓举", steps: "哑铃落地，伸髋伸膝爆发上拉贴身，翻肘举过头锁定，换手交替进行", keyPoints: nil,
          scaling: "减重 / 哑铃力量抓举", prereqs: ["dumbbell_power_snatch"], rationale: "CF通用进阶", englishName: "Alternating Dumbbell Snatch",
          englishIntro: "An alternating single-arm dumbbell snatch", englishSteps: "Set the dumbbell on the floor; explosively extend the hips and knees to pull it close to the body, turn the elbow over to lock it out overhead, and alternate hands",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell power snatch"),
        s("alternating_kettlebell_snatch", "交替壶铃抓举", "wl_m08", .l3, "奥举", "次数",
          intro: "左右交替的单臂壶铃抓举", steps: "壶铃于两腿间摆起，伸髋发力过头翻腕锁定，下放回摆换手交替", keyPoints: nil,
          scaling: "减重 / 壶铃抓举", prereqs: ["kettlebell_snatch"], rationale: "CF通用进阶", englishName: "Alternating Kettlebell Snatch",
          englishIntro: "An alternating single-arm kettlebell snatch", englishSteps: "Swing the kettlebell from between the legs, drive through the hips to send it overhead, rotate the hand through, lock out, then lower into the backswing and alternate hands",
          englishKeyPoints: nil, englishScaling: "Reduce the load / kettlebell snatch"),
        s("push_jerk", "借力挺举", "wl_m05", .l3, "上肢推(过头)", "次数",
          intro: "借下蹲发力把杠铃送过头并下蹲接杠", steps: "前架微屈膝爆发蹬地推杠，快速下蹲至杠铃下方手臂锁定接住，站直", keyPoints: nil,
          scaling: "减重 / 借力推举", prereqs: ["shoulder_press", "push_press"], rationale: "CF通用进阶", englishName: "Push Jerk",
          englishIntro: "A jerk that uses a dip and drive to send the bar overhead, then receives it in a second dip", englishSteps: "From the front rack, dip slightly and drive hard through the legs to move the bar up, then quickly drop under it with arms locked out, stand tall to finish",
          englishKeyPoints: nil, englishScaling: "Reduce the load / push press"),
        s("power_clean", "力量翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "杠铃翻至前架位但不进入深蹲", steps: "蹬地拉起、伸髋耸肩快速翻肘，于高于平行的位置接杠至前架位，站直", keyPoints: "与翻站区别：在高于平行处接杠、不进入全深蹲；脊柱膝关节有伤者慎做",
          scaling: "减重 / 悬垂力量翻站", prereqs: ["deadlift", "hang_power_clean"], rationale: "CF通用进阶", englishName: "Power Clean",
          englishIntro: "A barbell clean to the front rack without receiving in a full squat", englishSteps: "Pull from the floor, extend the hips and shrug, then turn the elbows through quickly and receive the bar in the front rack above parallel before standing tall",
          englishKeyPoints: "Difference from a clean: received above parallel rather than in a full squat. Use caution with spine or knee injuries", englishScaling: "Reduce the load / hang power clean"),
        s("single_arm_db_overhead_lunge", "单臂哑铃过头弓步", "wl_m10", .l3, "弓步单腿", "次数",
          intro: "单臂哑铃锁定过头完成的弓步", steps: "单臂哑铃稳定锁定过头，向前或退步下蹲至后膝近地，蹬前脚起身", keyPoints: nil,
          scaling: "减重 / 前架弓步", prereqs: ["walking_lunge"], rationale: "CF通用进阶", englishName: "Single Arm Db Overhead Lunge",
          englishIntro: "A lunge performed with one dumbbell locked out overhead", englishSteps: "Lock one dumbbell out overhead with the arm stable; step forward or back into a lunge until the back knee is near the floor, then drive through the front foot to stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / front-rack lunge"),
        s("double_kettlebell_clean", "双壶铃翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "双手各持壶铃翻至肩架位", steps: "双壶铃于两腿间后摆，伸髋发力翻至肩前架位，全程背部挺直", keyPoints: "高难，建议在教练指导下纳入计划；腰椎受伤者慎做",
          scaling: "减重 / 单壶铃翻站", prereqs: ["kettlebell_high_pull", "front_squat"], rationale: "CF通用进阶", englishName: "Double Kettlebell Clean",
          englishIntro: "A double-kettlebell clean to the rack position", englishSteps: "Swing both kettlebells back between the legs, extend the hips to clean them to the front rack, and keep the back flat throughout",
          englishKeyPoints: "High skill; add it to training under coach guidance. Use caution with lumbar spine injuries", englishScaling: "Reduce the load / single-kettlebell clean"),
        s("dumbbell_squat_clean", "哑铃下蹲翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "双哑铃翻至肩并全深蹲接住", steps: "哑铃落地爆发上拉，下蹲在肩前接住，再伸髋伸膝站直", keyPoints: nil,
          scaling: "减重 / 哑铃翻站", prereqs: ["dumbbell_clean", "front_squat"], rationale: "CF通用进阶", englishName: "Dumbbell Squat Clean",
          englishIntro: "A dumbbell clean received in a full squat", englishSteps: "Pull the dumbbells explosively from the floor, drop into a squat to receive them at the shoulders, then extend the hips and knees to stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell clean"),
        s("dumbbell_push_jerk", "哑铃借力挺举", "wl_m05", .l3, "上肢推(过头)", "次数",
          intro: "借腿部发力把双哑铃挺举过头", steps: "双哑铃置肩微屈膝下蹲，蹬地借力推过头锁定，再缓慢回到肩", keyPoints: nil,
          scaling: "减重 / 哑铃借力推举", prereqs: ["dumbbell_press", "dumbbell_push_press"], rationale: "CF通用进阶", englishName: "Dumbbell Push Jerk",
          englishIntro: "A dumbbell jerk using leg drive", englishSteps: "Hold the dumbbells at the shoulders, dip slightly, drive with the legs to push them overhead to lockout, then return slowly to the shoulders",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell push press"),
        s("dumbbell_power_snatch", "哑铃力量抓举", "wl_m08", .l3, "奥举", "次数",
          intro: "单臂哑铃一次性举过头、不深蹲", steps: "哑铃置两腿间下蹲，伸髋伸膝爆发上拉贴身，翻肘在高位将哑铃举过头锁定", keyPoints: "全程哑铃贴身、靠髋臀发力，避免把哑铃甩离身体",
          scaling: "减重 / 哑铃高拉至肩", prereqs: ["kettlebell_swing"], rationale: "CF通用进阶", englishName: "Dumbbell Power Snatch",
          englishIntro: "A single-arm dumbbell snatch received overhead without a deep squat", englishSteps: "Set the dumbbell between the legs, squat down, explosively extend the hips and knees to pull it close, turn the elbow over, and receive it overhead in a high position",
          englishKeyPoints: "Keep the dumbbell close throughout and use the hips and glutes to drive; avoid swinging the dumbbell away from the body", englishScaling: "Reduce the load / dumbbell high pull to the shoulder"),
        s("dumbbell_hang_clean_and_jerk", "哑铃悬垂翻站挺举", "wl_m08", .l3, "奥举", "次数",
          intro: "哑铃从悬垂位翻至肩再挺举过头", steps: "哑铃悬于大腿，伸髋翻至肩，微屈膝借力挺举过头锁定后站直", keyPoints: nil,
          scaling: "减重 / 拆成哑铃翻站+借力挺举", prereqs: ["dumbbell_clean", "dumbbell_push_jerk"], rationale: "CF通用进阶", englishName: "Dumbbell Hang Clean And Jerk",
          englishIntro: "A dumbbell clean from the hang followed by a jerk overhead", englishSteps: "Start with the dumbbells hanging at the thighs, extend the hips to clean them to the shoulders, dip slightly, jerk them overhead to lockout, then stand tall",
          englishKeyPoints: nil, englishScaling: "Reduce the load / break into dumbbell clean + push jerk"),
        s("dumbbell_thruster", "哑铃深蹲推举", "wl_m09", .l3, "复合全身", "次数",
          intro: "哑铃前蹲接借力推举的复合动作", steps: "双哑铃置肩下蹲至大腿过平行，蹬地起身借力把哑铃推举过头锁定，落回肩", keyPoints: nil,
          scaling: "减重 / 拆成哑铃深蹲+推举", prereqs: ["dumbbell_squat", "dumbbell_press"], rationale: "CF通用进阶", englishName: "Dumbbell Thruster",
          englishIntro: "A dumbbell front squat directly into a push press", englishSteps: "Hold the dumbbells at the shoulders, squat below parallel, then drive up and use the legs to press the dumbbells overhead to lockout; return them to the shoulders",
          englishKeyPoints: nil, englishScaling: "Reduce the load / break into dumbbell squat + press"),
        s("kettlebell_snatch", "壶铃抓举", "wl_m08", .l3, "奥举", "次数",
          intro: "将壶铃一次性摆举至头顶锁定", steps: "壶铃置两脚间屈髋握住，伸髋伸膝摆起，过肩时翻腕送至头顶手臂锁定", keyPoints: nil,
          scaling: "减重 / 壶铃高拉", prereqs: ["kettlebell_swing", "kettlebell_high_pull"], rationale: "CF通用进阶", englishName: "Kettlebell Snatch",
          englishIntro: "A kettlebell lifted from swing to overhead lockout in one motion", englishSteps: "Place the kettlebell between the feet, hinge and grip it, extend the hips and knees to swing it up, then rotate the hand through above the shoulder and lock out overhead",
          englishKeyPoints: nil, englishScaling: "Reduce the load / kettlebell high pull"),
        s("kettlebell_thruster", "壶铃深蹲推举", "wl_m09", .l3, "复合全身", "次数",
          intro: "双壶铃深蹲接推举过头的复合动作", steps: "双壶铃置肩架位下蹲至大腿过平行，蹬地起身借力把壶铃推举过头锁定，落回肩", keyPoints: "调动大量大小肌群、能耗高，并能强化稳定肌群",
          scaling: "减重 / 单壶铃高脚杯深蹲推举", prereqs: ["kettlebell_goblet_thruster"], rationale: "CF通用进阶", englishName: "Kettlebell Thruster",
          englishIntro: "A double-kettlebell squat directly into an overhead press", englishSteps: "Rack both kettlebells at the shoulders, squat below parallel, then drive up and use the legs to press them overhead to lockout; return them to the rack",
          englishKeyPoints: "Recruits many large and small muscle groups, has high energy cost, and strengthens stabilizers", englishScaling: "Reduce the load / single-kettlebell goblet thruster"),
        s("kettlebell_clean_and_jerk", "壶铃翻站挺举", "wl_m08", .l3, "奥举", "次数",
          intro: "壶铃翻至肩后再挺举过头", steps: "伸髋翻壶铃至肩架位，微屈膝爆发挺举过头手臂锁定，下蹲接住后站直", keyPoints: nil,
          scaling: "减重 / 拆成壶铃高拉+借力推举", prereqs: ["kettlebell_high_pull", "push_press"], rationale: "CF通用进阶", englishName: "Kettlebell Clean And Jerk",
          englishIntro: "A kettlebell clean to the rack followed by a jerk overhead", englishSteps: "Clean the kettlebell to the rack, dip slightly, drive explosively to jerk it overhead to arm lockout, receive it in a dip, then stand tall",
          englishKeyPoints: nil, englishScaling: "Reduce the load / break into kettlebell high pull + push press"),
        s("hang_power_clean", "悬垂力量翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "从悬垂位翻站至前架位、不进入深蹲", steps: "杠铃悬于大腿，伸髋伸膝耸肩拉起，快速翻肘在高位接杠至前架位站直", keyPoints: "从悬垂位接杠、不进入全深蹲；脊柱膝关节有伤者慎做",
          scaling: "减重 / 高悬垂位翻站", prereqs: ["deadlift", "kettlebell_swing"], rationale: "CF通用进阶", englishName: "Hang Power Clean",
          englishIntro: "A clean from the hang to the front rack without a full squat", englishSteps: "Start with the bar hanging at the thighs; extend the hips and knees, shrug, pull up, and turn the elbows through quickly to receive the bar high in the front rack, then stand",
          englishKeyPoints: "Received from the hang above parallel, without a full squat. Use caution with spine or knee injuries", englishScaling: "Reduce the load / high-hang power clean"),
        s("hang_clean", "悬垂翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "从悬垂位翻站至前架位", steps: "杠铃悬于大腿，伸髋伸膝耸肩拉起，快速翻肘接杠至前架位站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 悬垂力量翻站", prereqs: ["hang_power_clean", "front_squat"], rationale: "CF通用进阶", englishName: "Hang Clean",
          englishIntro: "A clean from the hang to the front rack", englishSteps: "Start with the bar hanging at the thighs; extend the hips and knees, shrug, pull up, turn the elbows through quickly, and receive the bar in the front rack, then stand",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / hang power clean"),
        s("thruster", "深蹲推举", "wl_m09", .l3, "复合全身", "次数",
          intro: "前蹲接借力推举的复合动作", steps: "前架持杠下蹲至髋低于膝，蹬地起身借惯性将杠铃推举过头锁定，落回肩部接下一次", keyPoints: "结合了翻站、前蹲与借力推，对心肺要求高；加重练力量、减重练耐力",
          scaling: "减重 / 哑铃深蹲推举 / 拆成前蹲+借力推举", prereqs: ["front_squat", "push_press"], rationale: "CF通用进阶", englishName: "Thruster",
          englishIntro: "A front squat directly into a push press", englishSteps: "Hold the bar in the front rack, squat until the hips are below the knees, then drive up and use the momentum to press the bar overhead to lockout; return it to the shoulders for the next rep",
          englishKeyPoints: "Combines the clean, front squat, and push press, with high cardiovascular demand; use heavier loads for strength and lighter loads for endurance", englishScaling: "Reduce the load / dumbbell thruster / break into front squat + push press"),
        s("clean", "翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "将杠铃从地面翻至前架位的奥举基础动作", steps: "蹬地拉起贴身、伸髋耸肩，快速翻肘下蹲在前架位接杠，蹬地站直", keyPoints: "翻站是奥举基础动作；脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 力量翻站", prereqs: ["power_clean", "front_squat"], rationale: "CF通用进阶", englishName: "Clean",
          englishIntro: "A foundational Olympic lifting movement that brings the barbell from the floor to the front rack", englishSteps: "Drive the bar from the floor close to the body, extend the hips and shrug, turn the elbows through quickly, receive it in the front rack in a squat, then stand",
          englishKeyPoints: "The clean is a foundational Olympic lift; use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / power clean"),
        s("muscle_snatch", "肌肉抓举", "wl_m08", .l3, "奥举", "次数",
          intro: "不下蹲、靠手臂将杠铃翻过头的抓举", steps: "抓举握距拉起，身体伸展后尽量高抬肘，翻腕把杠铃送至过头锁定，腿全程伸直", keyPoints: "全程腿伸直、保持对杠铃持续张力、动作连续无停顿",
          scaling: "减重 / 抓举高拉", prereqs: [], rationale: "CF通用进阶", englishName: "Muscle Snatch",
          englishIntro: "A snatch performed without dropping under the bar, relying on the arms to finish overhead", englishSteps: "Use a snatch grip to pull the bar; after extending the body, keep lifting the elbows high and turn the wrists over to send the bar overhead to lockout while the legs stay straight",
          englishKeyPoints: "Keep the legs straight throughout, maintain continuous tension on the bar, and move smoothly without pausing", englishScaling: "Reduce the load / snatch high pull"),
        s("muscle_clean", "肌肉翻站", "wl_m08", .l3, "奥举", "次数",
          intro: "不下蹲、靠手臂把杠铃翻至肩", steps: "蹬地耸肩高抬肘把杠铃拉至上胸，快速翻肘在前架位接住，腿不下蹲", keyPoints: "全程腿伸直、动作连续，肘尽量高抬",
          scaling: "减重 / 翻站高拉", prereqs: ["deadlift", "kettlebell_swing"], rationale: "CF通用进阶", englishName: "Muscle Clean",
          englishIntro: "A clean performed without dropping under the bar, relying on the arms to bring the bar to the shoulders", englishSteps: "Drive and shrug to pull the bar to the upper chest with high elbows, then turn the elbows through quickly to receive it in the front rack without dipping the legs",
          englishKeyPoints: "Keep the legs straight throughout, move continuously, and lift the elbows as high as possible", englishScaling: "Reduce the load / clean high pull"),
        s("push_jerk_behind_head", "颈后借力挺举", "wl_m05", .l3, "上肢推(过头)", "次数",
          intro: "杠铃置颈后的借力挺举", steps: "杠铃置斜方肌微屈膝下蹲，蹬地推过头、分腿接杠锁定后收脚站直", keyPoints: nil,
          scaling: "减重 / 借力挺举", prereqs: ["push_jerk"], rationale: "CF通用进阶", englishName: "Push Jerk Behind Head",
          englishIntro: "A push jerk with the barbell starting behind the neck", englishSteps: "Place the bar on the traps behind the neck, dip slightly, drive the bar overhead, receive it in a split with the arms locked out, then recover the feet to stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / push jerk"),
        s("squat_clean", "下蹲翻站", "wl_m08", .l4, "奥举", "次数",
          intro: "翻站接杠后落入全深蹲再起立", steps: "蹬地拉起、伸髋耸肩，快速下蹲在前架位接住杠铃，蹬地站直", keyPoints: "翻站后落入全深蹲再起立；脊柱膝关节有伤者慎做",
          scaling: "减重 / 力量翻站", prereqs: ["power_clean", "front_squat"], rationale: "CF通用进阶", englishName: "Squat Clean",
          englishIntro: "A clean received in a full squat before standing", englishSteps: "Pull from the floor, extend the hips and shrug, then drop quickly under the bar to receive it in the front rack and stand",
          englishKeyPoints: "Receive the bar in a full squat after the clean, then stand; use caution with spine or knee injuries", englishScaling: "Reduce the load / power clean"),
        s("split_jerk", "分腿挺举", "wl_m05", .l4, "上肢推(过头)", "次数",
          intro: "下蹲发力、前后分腿接杠的挺举", steps: "前架微屈膝下蹲爆发推杠，快速前后分腿在过头锁定位接住，再收脚站直", keyPoints: "目前最主流的竞技挺举方式",
          scaling: "减重 / 借力挺举", prereqs: ["push_press", "push_jerk"], rationale: "CF通用进阶", englishName: "Split Jerk",
          englishIntro: "A jerk that receives the bar overhead in a split stance", englishSteps: "From the front rack, dip and drive explosively, then split the feet front and back to receive the bar overhead at lockout before recovering the feet to stand",
          englishKeyPoints: "Currently the most common jerk style in competitive weightlifting", englishScaling: "Reduce the load / push jerk"),
        s("power_snatch", "力量抓举", "wl_m08", .l4, "奥举", "次数",
          intro: "杠铃一次性举过头、不进入深蹲", steps: "宽握拉起、伸髋耸肩，过头时翻腕在高于平行处接杠锁定，站直", keyPoints: nil,
          scaling: "减重 / 悬垂力量抓举", prereqs: ["overhead_squat", "hang_power_snatch"], rationale: "CF通用进阶", englishName: "Power Snatch",
          englishIntro: "A barbell snatch received overhead without a full squat", englishSteps: "Pull with a wide grip, extend the hips and shrug, then turn the wrists over and receive the bar overhead above parallel before standing tall",
          englishKeyPoints: nil, englishScaling: "Reduce the load / hang power snatch"),
        s("power_clean_and_jerk", "力量翻站挺举", "wl_m08", .l4, "奥举", "次数",
          intro: "力量翻站接挺举的奥举复合动作", steps: "翻站至前架位站直，再微屈膝爆发挺举过头锁定，下蹲接杠后站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 拆成力量翻站+挺举", prereqs: ["power_clean", "jerk"], rationale: "CF通用进阶", englishName: "Power Clean And Jerk",
          englishIntro: "A power clean followed by a jerk", englishSteps: "Power clean the bar to the front rack and stand; then dip and drive it overhead, receive it in a dip, and stand tall",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / break into power clean + jerk"),
        s("single_arm_db_overhead_squat", "单臂哑铃过头深蹲", "wl_m04", .l4, "深蹲", "次数",
          intro: "单臂将哑铃锁定过头完成深蹲", steps: "单臂把哑铃稳定锁定过头、贴近身体中线，肩部稳定下蹲后站直", keyPoints: nil,
          scaling: "减重 / 双臂过头深蹲", prereqs: ["overhead_squat"], rationale: "CF通用进阶", englishName: "Single Arm Db Overhead Squat",
          englishIntro: "A single-arm overhead squat with a dumbbell locked out overhead", englishSteps: "Lock one dumbbell out overhead close to the body midline; keep the shoulder stable, squat down, and stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / two-arm overhead squat"),
        s("dumbbell_squat_snatch", "哑铃下蹲抓举", "wl_m08", .l4, "奥举", "次数",
          intro: "单臂哑铃举过头并全深蹲接住", steps: "哑铃于两膝间，伸髋伸膝上拉贴身，下蹲在过头位接住锁定，蹬地站直", keyPoints: nil,
          scaling: "减重 / 哑铃力量抓举", prereqs: ["dumbbell_power_snatch", "overhead_squat"], rationale: "CF通用进阶", englishName: "Dumbbell Squat Snatch",
          englishIntro: "A single-arm dumbbell snatch received in a full squat", englishSteps: "Start with the dumbbell between the knees, extend the hips and knees to pull it close, then drop into a squat to receive it locked out overhead and stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell power snatch"),
        s("dumbbell_hang_squat_clean", "哑铃悬垂下蹲翻站", "wl_m08", .l4, "奥举", "次数",
          intro: "哑铃从悬垂位翻至肩并下蹲接住", steps: "哑铃悬于大腿，爆发上拉下蹲在肩前接住，再伸髋伸膝站直", keyPoints: nil,
          scaling: "减重 / 哑铃下蹲翻站", prereqs: ["dumbbell_squat_clean"], rationale: "CF通用进阶", englishName: "Dumbbell Hang Squat Clean",
          englishIntro: "A dumbbell clean from the hang received in a full squat", englishSteps: "Start with the dumbbells hanging at the thighs; pull explosively and drop into a squat to receive them at the shoulders, then extend the hips and knees to stand",
          englishKeyPoints: nil, englishScaling: "Reduce the load / dumbbell squat clean"),
        s("hang_squat_clean", "悬垂下蹲翻站", "wl_m08", .l4, "奥举", "次数",
          intro: "从悬垂位翻站接全深蹲", steps: "杠铃悬于大腿，伸髋耸肩拉起，快速翻肘下蹲在前架位接杠，蹬地站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 悬垂翻站", prereqs: ["hang_clean", "front_squat"], rationale: "CF通用进阶", englishName: "Hang Squat Clean",
          englishIntro: "A hang clean received in a full squat", englishSteps: "Start with the bar hanging at the thighs; extend the hips and shrug, turn the elbows through quickly, and drop into a squat to receive the bar in the front rack, then stand",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / hang clean"),
        s("hang_power_snatch", "悬垂力量抓举", "wl_m08", .l4, "奥举", "次数",
          intro: "从悬垂位一次性举过头、不深蹲", steps: "杠铃悬于大腿，伸髋耸肩爆发上拉，过头翻腕在高位接杠锁定站直", keyPoints: nil,
          scaling: "减重 / 高悬垂位抓举", prereqs: ["overhead_squat"], rationale: "CF通用进阶", englishName: "Hang Power Snatch",
          englishIntro: "A barbell snatch from the hang received high, without a full squat", englishSteps: "Start with the bar hanging at the thighs; extend the hips and shrug, pull explosively, turn the wrists over, and receive the bar overhead in a high position before standing",
          englishKeyPoints: nil, englishScaling: "Reduce the load / high-hang snatch"),
        s("hang_snatch", "悬垂抓举", "wl_m08", .l4, "奥举", "次数",
          intro: "从悬垂位一次性举过头并下蹲接杠", steps: "杠铃悬于大腿，伸髋耸肩拉起，翻腕在下蹲位接杠锁定，站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 悬垂力量抓举", prereqs: ["hang_power_snatch", "overhead_squat"], rationale: "CF通用进阶", englishName: "Hang Snatch",
          englishIntro: "A barbell snatch from the hang received in a squat", englishSteps: "Start with the bar hanging at the thighs; extend the hips and shrug, pull, turn the wrists over, and receive the bar locked out overhead in a squat, then stand",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / hang power snatch"),
        s("jerk", "挺举", "wl_m05", .l4, "上肢推(过头)", "次数",
          intro: "将杠铃从肩送过头并下蹲接杠", steps: "前架微屈膝下蹲，爆发蹬地推杠过头，快速下蹲在手臂锁定位接住后站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 借力挺举", prereqs: ["push_press", "push_jerk"], rationale: "源数据+CF", englishName: "Jerk",
          englishIntro: "A movement that drives the barbell from the shoulders to overhead and receives it in a dip", englishSteps: "From the front rack, dip slightly, drive through the floor to send the bar overhead, then quickly drop under it with arms locked out and stand",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / push jerk"),
        s("clean_and_jerk", "翻站挺举", "wl_m08", .l4, "奥举", "次数",
          intro: "杠铃从地面翻至肩、再挺举过头的奥举动作", steps: "硬拉发力翻至前架位接住站直，再微屈膝爆发挺举过头、分腿接杠锁定后收脚站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 力量翻站挺举 / 拆成翻站+挺举", prereqs: ["clean", "jerk"], rationale: "CF通用进阶", englishName: "Clean And Jerk",
          englishIntro: "An Olympic lift that brings the barbell from the floor to the shoulders, then jerks it overhead", englishSteps: "Clean the bar from the floor to the front rack and stand; then dip, drive, and jerk it overhead, receiving in a split and recovering the feet to stand",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / power clean and jerk / break into clean + jerk"),
        s("cluster", "翻站接深蹲推举", "wl_m09", .l4, "复合全身", "次数",
          intro: "下蹲翻站接深蹲推举的复合动作", steps: "杠铃从地面翻至前架位下蹲，蹬地起身借力直接推举过头锁定", keyPoints: "每次从地面开始",
          scaling: "减重 / 拆成下蹲翻站+深蹲推举", prereqs: ["squat_clean", "thruster"], rationale: "CF通用进阶", englishName: "Cluster",
          englishIntro: "A squat clean directly into a thruster", englishSteps: "Clean the bar from the floor to the front rack, descend into a squat, then drive up and press directly overhead to lockout",
          englishKeyPoints: "Each rep starts from the floor", englishScaling: "Reduce the load / break into squat clean + thruster"),
        s("overhead_squat", "过头深蹲", "wl_m04", .l4, "深蹲", "次数",
          intro: "杠铃举过头完成深蹲，难度较高", steps: "抓举握距将杠铃锁定过头、肘部伸直，保持杠铃在头上方下蹲至髋低于膝，蹬地站直", keyPoints: "下蹲时髋折低于膝、全程肘部锁定；也是学习抓举接杠与改善灵活性的练习",
          scaling: "减重或持PVC / 前蹲+过头持杆", prereqs: ["front_squat"], rationale: "源数据+CF", englishName: "Overhead Squat",
          englishIntro: "A technically demanding squat with the barbell locked out overhead", englishSteps: "Use a snatch grip to lock the bar overhead with elbows straight; keep the bar over the midline, squat until the hips are below the knees, then stand",
          englishKeyPoints: "The hip crease passes below the knees and the elbows stay locked throughout; also useful for learning the snatch receiving position and improving mobility", englishScaling: "Reduce the load or use a PVC pipe / front squat + overhead PVC hold"),
        s("squat_snatch", "下蹲抓举", "wl_m08", .l5, "奥举", "次数",
          intro: "杠铃从地面一次性举过头并全深蹲接杠", steps: "宽握拉起贴身、三关节伸展，翻腕在过头深蹲位接住锁定，蹬地站直", keyPoints: "全程肘部锁定，过头深蹲位接杠",
          scaling: "减重 / 力量抓举", prereqs: ["power_snatch", "overhead_squat"], rationale: "CF通用进阶", englishName: "Squat Snatch",
          englishIntro: "A barbell snatch from the floor received in a full overhead squat", englishSteps: "Pull the bar from the floor with a wide grip, achieve triple extension of the hips, knees, and ankles, then turn the wrists over to receive it locked out in an overhead squat and stand",
          englishKeyPoints: "Keep the elbows locked throughout and receive the bar in the overhead squat position", englishScaling: "Reduce the load / power snatch"),
        s("hang_squat_snatch", "悬垂下蹲抓举", "wl_m08", .l5, "奥举", "次数",
          intro: "从悬垂位一次性举过头并全深蹲接杠", steps: "杠铃悬于大腿，伸髋耸肩拉起，翻腕在过头深蹲位接住锁定，站直", keyPoints: "脊柱、膝关节有创伤或破坏性改变者慎做",
          scaling: "减重 / 悬垂抓举", prereqs: ["hang_snatch", "overhead_squat"], rationale: "CF通用进阶", englishName: "Hang Squat Snatch",
          englishIntro: "A hang snatch received in a full overhead squat", englishSteps: "Start with the bar hanging at the thighs; extend the hips and shrug, pull, turn the wrists over, and receive it locked out in an overhead squat before standing",
          englishKeyPoints: "Use caution with traumatic injuries or degenerative changes in the spine or knees", englishScaling: "Reduce the load / hang snatch"),
        s("snatch", "抓举", "wl_m08", .l5, "奥举", "次数",
          intro: "杠铃从地面一次性举过头并下蹲接杠", steps: "宽握拉起贴身、三关节伸展，翻腕在过头深蹲位接住锁定，再蹬地站直", keyPoints: "技巧性很强的爆发动作，动作完美时重量会显得很轻",
          scaling: "减重 / 力量抓举", prereqs: ["power_snatch", "overhead_squat"], rationale: "CF通用进阶", englishName: "Snatch",
          englishIntro: "A barbell lift from the floor to overhead in one continuous motion, received in a squat", englishSteps: "Pull the bar from the floor with a wide grip, keep it close, achieve triple extension of the hips, knees, and ankles, turn the wrists over to receive it locked out in an overhead squat, then stand",
          englishKeyPoints: "A highly technical explosive lift; when performed well, the weight feels light", englishScaling: "Reduce the load / power snatch")
    ]

    // MARK: - Helper

    private static func s(_ id: String, _ name: String, _ sub: String, _ tier: SkillTier,
                          _ measure: String, _ pattern: String,
                          intro: String, steps: String, keyPoints: String?,
                          scaling: String, prereqs: [String] = [], rationale: String? = nil,
                          englishName: String = "",
                          englishIntro: String = "", englishSteps: String = "",
                          englishKeyPoints: String? = nil, englishScaling: String = "") -> SkillDefinition {
        // 注意：参数顺序 measure 在 pattern 之前是生成器约定；此处显式映射，避免歧义。
        SkillDefinition(
            id: id, name: name, englishName: englishName, tier: tier,
            categoryId: sub.hasPrefix("gym") ? "gymnastics" : "weightlifting",
            subcategoryId: sub, movementPattern: pattern, measure: measure,
            intro: intro, steps: steps, keyPoints: keyPoints,
            scaling: scaling, prerequisites: prereqs, prereqRationale: rationale,
            englishIntro: englishIntro, englishSteps: englishSteps,
            englishKeyPoints: englishKeyPoints, englishScaling: englishScaling
        )
    }
}
